# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PscArt2.0.X/UserInt/ui_Artes_Amostradas.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 541)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.CBArtes = QtWidgets.QComboBox(Form)
        self.CBArtes.setObjectName("CBArtes")
        self.gridLayout.addWidget(self.CBArtes, 3, 2, 1, 2)
        self.CBCentroOrigem = QtWidgets.QComboBox(Form)
        self.CBCentroOrigem.setObjectName("CBCentroOrigem")
        self.gridLayout.addWidget(self.CBCentroOrigem, 2, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 3, 1, 1)
        self.SBAmostradas = QtWidgets.QSpinBox(Form)
        self.SBAmostradas.setObjectName("SBAmostradas")
        self.gridLayout.addWidget(self.SBAmostradas, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.LEN_Seq_Saidas = QtWidgets.QLineEdit(Form)
        self.LEN_Seq_Saidas.setReadOnly(True)
        self.LEN_Seq_Saidas.setObjectName("LEN_Seq_Saidas")
        self.gridLayout.addWidget(self.LEN_Seq_Saidas, 0, 2, 1, 1)
        self.LEN_Sequencial = QtWidgets.QLineEdit(Form)
        self.LEN_Sequencial.setReadOnly(True)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.gridLayout.addWidget(self.LEN_Sequencial, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 3, 1, 1)
        self.SBArtes_N_activas = QtWidgets.QSpinBox(Form)
        self.SBArtes_N_activas.setObjectName("SBArtes_N_activas")
        self.gridLayout.addWidget(self.SBArtes_N_activas, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 2)
        self.SBArtes_act = QtWidgets.QSpinBox(Form)
        self.SBArtes_act.setObjectName("SBArtes_act")
        self.gridLayout.addWidget(self.SBArtes_act, 4, 2, 1, 1)
        self.PBEditar = QtWidgets.QPushButton(Form)
        self.PBEditar.setObjectName("PBEditar")
        self.gridLayout.addWidget(self.PBEditar, 0, 4, 2, 1)
        self.PBInseri = QtWidgets.QPushButton(Form)
        self.PBInseri.setObjectName("PBInseri")
        self.gridLayout.addWidget(self.PBInseri, 5, 4, 2, 1)
        self.PBGuardar = QtWidgets.QPushButton(Form)
        self.PBGuardar.setObjectName("PBGuardar")
        self.gridLayout.addWidget(self.PBGuardar, 2, 4, 3, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        self.PBVoltar = QtWidgets.QPushButton(Form)
        self.PBVoltar.setObjectName("PBVoltar")
        self.gridLayout_2.addWidget(self.PBVoltar, 2, 0, 1, 1)
        self.PBVagPesca = QtWidgets.QPushButton(Form)
        self.PBVagPesca.setObjectName("PBVagPesca")
        self.gridLayout_2.addWidget(self.PBVagPesca, 2, 1, 1, 1)
        self.PBCancelar = QtWidgets.QPushButton(Form)
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout_2.addWidget(self.PBCancelar, 2, 2, 1, 1)
        self.TVArtePescaAmostradas = QtWidgets.QTableView(Form)
        self.TVArtePescaAmostradas.setObjectName("TVArtePescaAmostradas")
        self.gridLayout_2.addWidget(self.TVArtePescaAmostradas, 1, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Artes de Pesca Amostradas"))
        self.label_5.setText(_translate("Form", "Artes nao Activas"))
        self.label_3.setText(_translate("Form", "Centro de Origem"))
        self.label.setText(_translate("Form", "Nº Sequencial"))
        self.label_2.setText(_translate("Form", "Nº Sequencial da Saida"))
        self.label_4.setText(_translate("Form", "Artes Activas"))
        self.label_7.setText(_translate("Form", "Arte"))
        self.label_6.setText(_translate("Form", "Amostradas"))
        self.PBEditar.setText(_translate("Form", "Editar"))
        self.PBInseri.setText(_translate("Form", "Inserir"))
        self.PBGuardar.setText(_translate("Form", "Guardar"))
        self.PBVoltar.setText(_translate("Form", "Voltar"))
        self.PBVagPesca.setText(_translate("Form", "Viagens das Pesca"))
        self.PBCancelar.setText(_translate("Form", "Cancelar"))

