# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PscArt2.0.X/UserInt/ui_artes.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 605)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.LECodigo = QtWidgets.QLineEdit(Dialog)
        self.LECodigo.setObjectName("LECodigo")
        self.gridLayout.addWidget(self.LECodigo, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.LENome = QtWidgets.QLineEdit(Dialog)
        self.LENome.setObjectName("LENome")
        self.gridLayout.addWidget(self.LENome, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.CBuniTrablho = QtWidgets.QComboBox(Dialog)
        self.CBuniTrablho.setObjectName("CBuniTrablho")
        self.gridLayout.addWidget(self.CBuniTrablho, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.CBUniEsforco = QtWidgets.QComboBox(Dialog)
        self.CBUniEsforco.setObjectName("CBUniEsforco")
        self.gridLayout.addWidget(self.CBUniEsforco, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.CBTipPesca = QtWidgets.QComboBox(Dialog)
        self.CBTipPesca.setObjectName("CBTipPesca")
        self.gridLayout.addWidget(self.CBTipPesca, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.LEDescricao = QtWidgets.QLineEdit(Dialog)
        self.LEDescricao.setObjectName("LEDescricao")
        self.gridLayout.addWidget(self.LEDescricao, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.LEComentarios = QtWidgets.QLineEdit(Dialog)
        self.LEComentarios.setObjectName("LEComentarios")
        self.gridLayout.addWidget(self.LEComentarios, 6, 1, 1, 1)
        self.CHBActivo = QtWidgets.QCheckBox(Dialog)
        self.CHBActivo.setObjectName("CHBActivo")
        self.gridLayout.addWidget(self.CHBActivo, 7, 1, 1, 1)
        self.TVartes = QtWidgets.QTableView(Dialog)
        self.TVartes.setObjectName("TVartes")
        self.gridLayout.addWidget(self.TVartes, 8, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.PBEditar = QtWidgets.QPushButton(self.splitter)
        self.PBEditar.setObjectName("PBEditar")
        self.PBGuardar = QtWidgets.QPushButton(self.splitter)
        self.PBGuardar.setObjectName("PBGuardar")
        self.PBAdicionar = QtWidgets.QPushButton(self.splitter)
        self.PBAdicionar.setObjectName("PBAdicionar")
        self.PBCancelar = QtWidgets.QPushButton(self.splitter)
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout.addWidget(self.splitter, 9, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Artes de Pesca"))
        self.label_11.setText(_translate("Dialog", "Codigo:"))
        self.label_8.setText(_translate("Dialog", "Nome:"))
        self.label_6.setText(_translate("Dialog", "Unidade de Trabalho:"))
        self.label_5.setText(_translate("Dialog", "Unidade de Esforco:"))
        self.label_7.setText(_translate("Dialog", "Tipo de Pesca:"))
        self.label_10.setText(_translate("Dialog", "Descricao:"))
        self.label_9.setText(_translate("Dialog", "Comentarios:"))
        self.CHBActivo.setText(_translate("Dialog", "Activo"))
        self.PBEditar.setText(_translate("Dialog", "Editar"))
        self.PBGuardar.setText(_translate("Dialog", "Guardar"))
        self.PBAdicionar.setText(_translate("Dialog", "Adicionar"))
        self.PBCancelar.setText(_translate("Dialog", "Cancelar"))

