# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_CalculoEstim.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FrmCalculoEst(object):
    def setupUi(self, FrmCalculoEst):
        FrmCalculoEst.setObjectName("FrmCalculoEst")
        FrmCalculoEst.resize(932, 447)
        self.groupBox = QtWidgets.QGroupBox(FrmCalculoEst)
        self.groupBox.setGeometry(QtCore.QRect(10, 6, 181, 434))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 161, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.CBAno_inicio = QtWidgets.QComboBox(self.groupBox_2)
        self.CBAno_inicio.setObjectName("CBAno_inicio")
        self.gridLayout.addWidget(self.CBAno_inicio, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.CBMes_inicio = QtWidgets.QComboBox(self.groupBox_2)
        self.CBMes_inicio.setObjectName("CBMes_inicio")
        self.gridLayout.addWidget(self.CBMes_inicio, 1, 1, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 161, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.CBAno_Fim = QtWidgets.QComboBox(self.groupBox_3)
        self.CBAno_Fim.setObjectName("CBAno_Fim")
        self.gridLayout_2.addWidget(self.CBAno_Fim, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.CBMes_Fim = QtWidgets.QComboBox(self.groupBox_3)
        self.CBMes_Fim.setObjectName("CBMes_Fim")
        self.gridLayout_2.addWidget(self.CBMes_Fim, 1, 1, 1, 2)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 310, 161, 49))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.CBPeriodoDia = QtWidgets.QComboBox(self.layoutWidget)
        self.CBPeriodoDia.setObjectName("CBPeriodoDia")
        self.gridLayout_4.addWidget(self.CBPeriodoDia, 1, 0, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 370, 161, 49))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.CBTipDia = QtWidgets.QComboBox(self.layoutWidget_2)
        self.CBTipDia.setObjectName("CBTipDia")
        self.gridLayout_5.addWidget(self.CBTipDia, 1, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 161, 49))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.CBAgrupamento = QtWidgets.QComboBox(self.layoutWidget1)
        self.CBAgrupamento.setObjectName("CBAgrupamento")
        self.gridLayout_3.addWidget(self.CBAgrupamento, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(FrmCalculoEst)
        self.groupBox_4.setGeometry(QtCore.QRect(198, 190, 271, 251))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TViewArtes = QtWidgets.QTableView(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TViewArtes.setFont(font)
        self.TViewArtes.setObjectName("TViewArtes")
        self.gridLayout_6.addWidget(self.TViewArtes, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(FrmCalculoEst)
        self.groupBox_5.setGeometry(QtCore.QRect(475, 190, 191, 251))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.TViewCategorias = QtWidgets.QTableView(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TViewCategorias.setFont(font)
        self.TViewCategorias.setObjectName("TViewCategorias")
        self.gridLayout_7.addWidget(self.TViewCategorias, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(FrmCalculoEst)
        self.groupBox_6.setGeometry(QtCore.QRect(710, 130, 213, 62))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.CHBCaptura = QtWidgets.QCheckBox(self.groupBox_6)
        self.CHBCaptura.setObjectName("CHBCaptura")
        self.gridLayout_15.addWidget(self.CHBCaptura, 0, 0, 1, 1)
        self.GBCompEsp = QtWidgets.QGroupBox(FrmCalculoEst)
        self.GBCompEsp.setGeometry(QtCore.QRect(674, 192, 249, 250))
        self.GBCompEsp.setAlignment(QtCore.Qt.AlignCenter)
        self.GBCompEsp.setCheckable(True)
        self.GBCompEsp.setObjectName("GBCompEsp")
        self.label_11 = QtWidgets.QLabel(self.GBCompEsp)
        self.label_11.setGeometry(QtCore.QRect(13, 27, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(self.GBCompEsp)
        self.label_22.setGeometry(QtCore.QRect(10, 47, 58, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setObjectName("label_22")
        self.layoutWidget2 = QtWidgets.QWidget(self.GBCompEsp)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 150, 231, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget2.sizePolicy().hasHeightForWidth())
        self.layoutWidget2.setSizePolicy(sizePolicy)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.DSBMin = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DSBMin.sizePolicy().hasHeightForWidth())
        self.DSBMin.setSizePolicy(sizePolicy)
        self.DSBMin.setObjectName("DSBMin")
        self.gridLayout_13.addWidget(self.DSBMin, 2, 1, 1, 1)
        self.DSBMax = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DSBMax.sizePolicy().hasHeightForWidth())
        self.DSBMax.setSizePolicy(sizePolicy)
        self.DSBMax.setObjectName("DSBMax")
        self.gridLayout_13.addWidget(self.DSBMax, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 0, 0, 1, 2)
        self.layoutWidget3 = QtWidgets.QWidget(self.GBCompEsp)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 70, 231, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 1, 0, 1, 1)
        self.CBSexo = MyComboBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CBSexo.setFont(font)
        self.CBSexo.setObjectName("CBSexo")
        self.gridLayout_12.addWidget(self.CBSexo, 1, 1, 1, 1)
        self.CBEspecie = MyComboBox(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.CBEspecie.setFont(font)
        self.CBEspecie.setObjectName("CBEspecie")
        self.gridLayout_12.addWidget(self.CBEspecie, 0, 1, 1, 1)
        self.TBEspecies = QtWidgets.QToolButton(self.layoutWidget3)
        self.TBEspecies.setObjectName("TBEspecies")
        self.gridLayout_12.addWidget(self.TBEspecies, 0, 2, 1, 1)
        self.TBSexo = QtWidgets.QToolButton(self.layoutWidget3)
        self.TBSexo.setObjectName("TBSexo")
        self.gridLayout_12.addWidget(self.TBSexo, 1, 2, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(self.GBCompEsp)
        self.layoutWidget4.setGeometry(QtCore.QRect(78, 46, 161, 21))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.RBTodos = QtWidgets.QRadioButton(self.layoutWidget4)
        self.RBTodos.setChecked(False)
        self.RBTodos.setObjectName("RBTodos")
        self.gridLayout_8.addWidget(self.RBTodos, 0, 0, 1, 1)
        self.RBAmost = QtWidgets.QRadioButton(self.layoutWidget4)
        self.RBAmost.setChecked(True)
        self.RBAmost.setObjectName("RBAmost")
        self.gridLayout_8.addWidget(self.RBAmost, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(FrmCalculoEst)
        self.groupBox_8.setGeometry(QtCore.QRect(390, 10, 301, 181))
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.TViewEstratos = QtWidgets.QTableView(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TViewEstratos.setFont(font)
        self.TViewEstratos.setObjectName("TViewEstratos")
        self.gridLayout_9.addWidget(self.TViewEstratos, 0, 0, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(FrmCalculoEst)
        self.layoutWidget5.setGeometry(QtCore.QRect(200, 30, 181, 49))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.CBEstratificacao = QtWidgets.QComboBox(self.layoutWidget5)
        self.CBEstratificacao.setObjectName("CBEstratificacao")
        self.gridLayout_10.addWidget(self.CBEstratificacao, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 0, 1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(FrmCalculoEst)
        self.layoutWidget6.setGeometry(QtCore.QRect(760, 22, 111, 101))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.PBSair = QtWidgets.QPushButton(self.layoutWidget6)
        self.PBSair.setObjectName("PBSair")
        self.gridLayout_11.addWidget(self.PBSair, 2, 0, 1, 1)
        self.PBCalcular = QtWidgets.QPushButton(self.layoutWidget6)
        self.PBCalcular.setObjectName("PBCalcular")
        self.gridLayout_11.addWidget(self.PBCalcular, 0, 0, 1, 1)
        self.PBOpcoes = QtWidgets.QPushButton(self.layoutWidget6)
        self.PBOpcoes.setObjectName("PBOpcoes")
        self.gridLayout_11.addWidget(self.PBOpcoes, 1, 0, 1, 1)

        self.retranslateUi(FrmCalculoEst)
        QtCore.QMetaObject.connectSlotsByName(FrmCalculoEst)

    def retranslateUi(self, FrmCalculoEst):
        _translate = QtCore.QCoreApplication.translate
        FrmCalculoEst.setWindowTitle(_translate("FrmCalculoEst", "Calculo das Estimativas"))
        self.groupBox.setTitle(_translate("FrmCalculoEst", "Periodos "))
        self.groupBox_2.setTitle(_translate("FrmCalculoEst", "Desde:"))
        self.label.setText(_translate("FrmCalculoEst", "Ano:"))
        self.label_2.setText(_translate("FrmCalculoEst", "Mes:"))
        self.groupBox_3.setTitle(_translate("FrmCalculoEst", "Ate:"))
        self.label_3.setText(_translate("FrmCalculoEst", "Ano:"))
        self.label_4.setText(_translate("FrmCalculoEst", "Mes:"))
        self.label_6.setText(_translate("FrmCalculoEst", "Periodo do Dia:"))
        self.label_7.setText(_translate("FrmCalculoEst", "Tipo de Dia:"))
        self.label_5.setText(_translate("FrmCalculoEst", "Agrupamento:"))
        self.groupBox_4.setTitle(_translate("FrmCalculoEst", "Artes"))
        self.groupBox_5.setTitle(_translate("FrmCalculoEst", "Categorias"))
        self.groupBox_6.setTitle(_translate("FrmCalculoEst", "Estimativas"))
        self.CHBCaptura.setText(_translate("FrmCalculoEst", "Captura/Esforco"))
        self.GBCompEsp.setTitle(_translate("FrmCalculoEst", "Composicao Especifica"))
        self.label_11.setText(_translate("FrmCalculoEst", "Distribuicao dos Comprimentos"))
        self.label_22.setText(_translate("FrmCalculoEst", "Especies:"))
        self.DSBMin.setSuffix(_translate("FrmCalculoEst", " CM"))
        self.DSBMax.setSuffix(_translate("FrmCalculoEst", " CM"))
        self.label_14.setText(_translate("FrmCalculoEst", "Max:"))
        self.label_15.setText(_translate("FrmCalculoEst", "Min:"))
        self.label_12.setText(_translate("FrmCalculoEst", "Intervalo"))
        self.label_10.setText(_translate("FrmCalculoEst", "Especies:"))
        self.label_16.setText(_translate("FrmCalculoEst", "Sexo:"))
        self.TBEspecies.setText(_translate("FrmCalculoEst", "..."))
        self.TBSexo.setText(_translate("FrmCalculoEst", "..."))
        self.RBTodos.setText(_translate("FrmCalculoEst", "Todas"))
        self.RBAmost.setText(_translate("FrmCalculoEst", "Amostr."))
        self.groupBox_8.setTitle(_translate("FrmCalculoEst", "Estratos Geograficos"))
        self.label_8.setText(_translate("FrmCalculoEst", "Estratificacao"))
        self.PBSair.setText(_translate("FrmCalculoEst", "Sair"))
        self.PBCalcular.setText(_translate("FrmCalculoEst", "Calcular"))
        self.PBOpcoes.setText(_translate("FrmCalculoEst", "Opcoes"))

from CustomWidgets import MyComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmCalculoEst = QtWidgets.QWidget()
    ui = Ui_FrmCalculoEst()
    ui.setupUi(FrmCalculoEst)
    FrmCalculoEst.show()
    sys.exit(app.exec_())

