# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_especies_POT.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(648, 325)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 1)
        self.PTEComentarios = QtWidgets.QPlainTextEdit(Form)
        self.PTEComentarios.setObjectName("PTEComentarios")
        self.gridLayout_4.addWidget(self.PTEComentarios, 1, 2, 1, 3)
        self.PBCancelar = QtWidgets.QPushButton(Form)
        self.PBCancelar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/003-error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBCancelar.setIcon(icon)
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout_4.addWidget(self.PBCancelar, 2, 2, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.DSBMaximo_2 = QtWidgets.QDoubleSpinBox(Form)
        self.DSBMaximo_2.setMaximum(99999.99)
        self.DSBMaximo_2.setObjectName("DSBMaximo_2")
        self.gridLayout_2.addWidget(self.DSBMaximo_2, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 1, 1, 1)
        self.CHBActivo = QtWidgets.QCheckBox(Form)
        self.CHBActivo.setObjectName("CHBActivo")
        self.gridLayout_2.addWidget(self.CHBActivo, 5, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.DSBMaixmo = QtWidgets.QDoubleSpinBox(Form)
        self.DSBMaixmo.setMaximum(99999.99)
        self.DSBMaixmo.setObjectName("DSBMaixmo")
        self.gridLayout_2.addWidget(self.DSBMaixmo, 3, 2, 1, 1)
        self.LEFamila = QtWidgets.QLineEdit(Form)
        self.LEFamila.setMaxLength(25)
        self.LEFamila.setObjectName("LEFamila")
        self.gridLayout_2.addWidget(self.LEFamila, 0, 1, 1, 2)
        self.LEGenus = QtWidgets.QLineEdit(Form)
        self.LEGenus.setMaxLength(25)
        self.LEGenus.setObjectName("LEGenus")
        self.gridLayout_2.addWidget(self.LEGenus, 1, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.LENome = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LENome.sizePolicy().hasHeightForWidth())
        self.LENome.setSizePolicy(sizePolicy)
        self.LENome.setMaxLength(25)
        self.LENome.setObjectName("LENome")
        self.gridLayout_2.addWidget(self.LENome, 2, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 1, 1, 1)
        self.DSBComum = QtWidgets.QDoubleSpinBox(Form)
        self.DSBComum.setMaximum(99999.99)
        self.DSBComum.setObjectName("DSBComum")
        self.gridLayout.addWidget(self.DSBComum, 4, 2, 1, 1)
        self.CHBAnalize = QtWidgets.QCheckBox(Form)
        self.CHBAnalize.setObjectName("CHBAnalize")
        self.gridLayout.addWidget(self.CHBAnalize, 5, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 1, 1, 1)
        self.DSBMinimo = QtWidgets.QDoubleSpinBox(Form)
        self.DSBMinimo.setMaximum(99999.99)
        self.DSBMinimo.setObjectName("DSBMinimo")
        self.gridLayout.addWidget(self.DSBMinimo, 3, 2, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 2, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.CBHabitat = QtWidgets.QComboBox(Form)
        self.CBHabitat.setObjectName("CBHabitat")
        self.gridLayout.addWidget(self.CBHabitat, 2, 1, 1, 2)
        self.LEEspecies = QtWidgets.QLineEdit(Form)
        self.LEEspecies.setMaxLength(50)
        self.LEEspecies.setObjectName("LEEspecies")
        self.gridLayout.addWidget(self.LEEspecies, 1, 1, 1, 2)
        self.LECodigo = QtWidgets.QLineEdit(Form)
        self.LECodigo.setMaxLength(5)
        self.LECodigo.setObjectName("LECodigo")
        self.gridLayout.addWidget(self.LECodigo, 0, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.PBGuardar = QtWidgets.QPushButton(Form)
        self.PBGuardar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/002-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBGuardar.setIcon(icon1)
        self.PBGuardar.setObjectName("PBGuardar")
        self.gridLayout_4.addWidget(self.PBGuardar, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Especies"))
        self.label_4.setText(_translate("Form", "Comentarios:"))
        self.PTEComentarios.setPlaceholderText(_translate("Form", "Ex:Nota, Obs…"))
        self.label.setText(_translate("Form", "Familia:"))
        self.DSBMaximo_2.setSpecialValueText(_translate("Form", "-.-- cm"))
        self.DSBMaximo_2.setSuffix(_translate("Form", " cm"))
        self.label_10.setText(_translate("Form", "maximo:"))
        self.CHBActivo.setText(_translate("Form", "Activo"))
        self.label_7.setText(_translate("Form", "Nome:"))
        self.DSBMaixmo.setSpecialValueText(_translate("Form", "-.-- cm"))
        self.DSBMaixmo.setSuffix(_translate("Form", " cm"))
        self.LEFamila.setPlaceholderText(_translate("Form", "Ex:Nome da Familia"))
        self.LEGenus.setPlaceholderText(_translate("Form", "Ex:Nome do  Genus"))
        self.label_12.setText(_translate("Form", "maximo:"))
        self.label_3.setText(_translate("Form", "Genus:"))
        self.LENome.setPlaceholderText(_translate("Form", "Ex:Nome Especie"))
        self.label_9.setText(_translate("Form", "Minimo:"))
        self.DSBComum.setSpecialValueText(_translate("Form", "-.-- cm"))
        self.DSBComum.setSuffix(_translate("Form", " cm"))
        self.CHBAnalize.setText(_translate("Form", "Analizar Composicao Especifica"))
        self.label_13.setText(_translate("Form", "Comum:"))
        self.DSBMinimo.setSpecialValueText(_translate("Form", "-.-- cm"))
        self.DSBMinimo.setSuffix(_translate("Form", " cm"))
        self.label_8.setText(_translate("Form", "Comprimentos"))
        self.label_11.setText(_translate("Form", "Intervalo de classes "))
        self.label_6.setText(_translate("Form", "Habitat:"))
        self.label_5.setText(_translate("Form", "Especies:"))
        self.label_2.setText(_translate("Form", "codigo:"))
        self.LEEspecies.setPlaceholderText(_translate("Form", "Ex:Nome Especie"))
        self.LECodigo.setPlaceholderText(_translate("Form", "Ex:AAAAA"))

import icons_rc
