# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_frmSort.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 587)
        self.gridLayout_7 = QtWidgets.QGridLayout(Form)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.RBDsc6 = QtWidgets.QRadioButton(self.groupBox)
        self.RBDsc6.setObjectName("RBDsc6")
        self.gridLayout_6.addWidget(self.RBDsc6, 0, 1, 1, 1)
        self.RBAsc6 = QtWidgets.QRadioButton(self.groupBox)
        self.RBAsc6.setChecked(False)
        self.RBAsc6.setObjectName("RBAsc6")
        self.gridLayout_6.addWidget(self.RBAsc6, 0, 0, 1, 1)
        self.RBNone_6 = QtWidgets.QRadioButton(self.groupBox)
        self.RBNone_6.setChecked(True)
        self.RBNone_6.setObjectName("RBNone_6")
        self.gridLayout_6.addWidget(self.RBNone_6, 0, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_6.addWidget(self.line_6, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox, 8, 0, 1, 2)
        self.groupBox1 = QtWidgets.QGroupBox(Form)
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.RBDsc3 = QtWidgets.QRadioButton(self.groupBox1)
        self.RBDsc3.setObjectName("RBDsc3")
        self.gridLayout_3.addWidget(self.RBDsc3, 0, 1, 1, 1)
        self.RBAsc3 = QtWidgets.QRadioButton(self.groupBox1)
        self.RBAsc3.setChecked(False)
        self.RBAsc3.setObjectName("RBAsc3")
        self.gridLayout_3.addWidget(self.RBAsc3, 0, 0, 1, 1)
        self.RBNone_3 = QtWidgets.QRadioButton(self.groupBox1)
        self.RBNone_3.setChecked(True)
        self.RBNone_3.setObjectName("RBNone_3")
        self.gridLayout_3.addWidget(self.RBNone_3, 0, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox1, 4, 0, 1, 2)
        self.groupBox2 = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox2.setFont(font)
        self.groupBox2.setFlat(True)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout.setObjectName("gridLayout")
        self.RBDsc1 = QtWidgets.QRadioButton(self.groupBox2)
        self.RBDsc1.setObjectName("RBDsc1")
        self.gridLayout.addWidget(self.RBDsc1, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.RBNone_1 = QtWidgets.QRadioButton(self.groupBox2)
        self.RBNone_1.setChecked(True)
        self.RBNone_1.setObjectName("RBNone_1")
        self.gridLayout.addWidget(self.RBNone_1, 0, 2, 1, 1)
        self.RBAsc1 = QtWidgets.QRadioButton(self.groupBox2)
        self.RBAsc1.setChecked(False)
        self.RBAsc1.setObjectName("RBAsc1")
        self.gridLayout.addWidget(self.RBAsc1, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox2, 0, 0, 1, 2)
        self.groupBox3 = QtWidgets.QGroupBox(Form)
        self.groupBox3.setFlat(True)
        self.groupBox3.setObjectName("groupBox3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.RBDsc4 = QtWidgets.QRadioButton(self.groupBox3)
        self.RBDsc4.setObjectName("RBDsc4")
        self.gridLayout_4.addWidget(self.RBDsc4, 0, 1, 1, 1)
        self.RBAsc4 = QtWidgets.QRadioButton(self.groupBox3)
        self.RBAsc4.setChecked(False)
        self.RBAsc4.setObjectName("RBAsc4")
        self.gridLayout_4.addWidget(self.RBAsc4, 0, 0, 1, 1)
        self.RBNone_4 = QtWidgets.QRadioButton(self.groupBox3)
        self.RBNone_4.setChecked(True)
        self.RBNone_4.setObjectName("RBNone_4")
        self.gridLayout_4.addWidget(self.RBNone_4, 0, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox3, 6, 0, 1, 2)
        self.groupBox4 = QtWidgets.QGroupBox(Form)
        self.groupBox4.setFlat(True)
        self.groupBox4.setObjectName("groupBox4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.RBAsc2 = QtWidgets.QRadioButton(self.groupBox4)
        self.RBAsc2.setChecked(False)
        self.RBAsc2.setObjectName("RBAsc2")
        self.gridLayout_2.addWidget(self.RBAsc2, 0, 0, 1, 1)
        self.RBDsc2 = QtWidgets.QRadioButton(self.groupBox4)
        self.RBDsc2.setObjectName("RBDsc2")
        self.gridLayout_2.addWidget(self.RBDsc2, 0, 1, 1, 1)
        self.RBNone_2 = QtWidgets.QRadioButton(self.groupBox4)
        self.RBNone_2.setChecked(True)
        self.RBNone_2.setObjectName("RBNone_2")
        self.gridLayout_2.addWidget(self.RBNone_2, 0, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox4)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox4, 2, 0, 1, 2)
        self.groupBox5 = QtWidgets.QGroupBox(Form)
        self.groupBox5.setFlat(True)
        self.groupBox5.setObjectName("groupBox5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.RBDsc5 = QtWidgets.QRadioButton(self.groupBox5)
        self.RBDsc5.setObjectName("RBDsc5")
        self.gridLayout_5.addWidget(self.RBDsc5, 0, 1, 1, 1)
        self.RBAsc5 = QtWidgets.QRadioButton(self.groupBox5)
        self.RBAsc5.setChecked(False)
        self.RBAsc5.setObjectName("RBAsc5")
        self.gridLayout_5.addWidget(self.RBAsc5, 0, 0, 1, 1)
        self.RBNone_5 = QtWidgets.QRadioButton(self.groupBox5)
        self.RBNone_5.setChecked(True)
        self.RBNone_5.setObjectName("RBNone_5")
        self.gridLayout_5.addWidget(self.RBNone_5, 0, 2, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_5.addWidget(self.line_5, 1, 0, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox5, 7, 0, 1, 2)
        self.PBFechar = QtWidgets.QPushButton(Form)
        self.PBFechar.setObjectName("PBFechar")
        self.gridLayout_7.addWidget(self.PBFechar, 9, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sort"))
        self.groupBox.setTitle(_translate("Form", "Dia da Semana"))
        self.RBDsc6.setText(_translate("Form", "Descendente"))
        self.RBAsc6.setText(_translate("Form", "Ascendente"))
        self.RBNone_6.setText(_translate("Form", "Nenhum"))
        self.groupBox1.setTitle(_translate("Form", "Registador"))
        self.RBDsc3.setText(_translate("Form", "Descendente"))
        self.RBAsc3.setText(_translate("Form", "Ascendente"))
        self.RBNone_3.setText(_translate("Form", "Nenhum"))
        self.groupBox2.setTitle(_translate("Form", "Data"))
        self.RBDsc1.setText(_translate("Form", "Descendente"))
        self.RBNone_1.setText(_translate("Form", "Nenhum"))
        self.RBAsc1.setText(_translate("Form", "Ascendente"))
        self.groupBox3.setTitle(_translate("Form", "Inicio"))
        self.RBDsc4.setText(_translate("Form", "Descendente"))
        self.RBAsc4.setText(_translate("Form", "Ascendente"))
        self.RBNone_4.setText(_translate("Form", "Nenhum"))
        self.groupBox4.setTitle(_translate("Form", "Centro de Pesca"))
        self.RBAsc2.setText(_translate("Form", "Ascendente"))
        self.RBDsc2.setText(_translate("Form", "Descendente"))
        self.RBNone_2.setText(_translate("Form", "Nenhum"))
        self.groupBox5.setTitle(_translate("Form", "Fim"))
        self.RBDsc5.setText(_translate("Form", "Descendente"))
        self.RBAsc5.setText(_translate("Form", "Ascendente"))
        self.RBNone_5.setText(_translate("Form", "Nenhum"))
        self.PBFechar.setText(_translate("Form", "Fechar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

