# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_Ficha_Recolha_Part_II.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1012, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 981, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.GLViagens = QtWidgets.QGridLayout(self.layoutWidget)
        self.GLViagens.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLViagens.setContentsMargins(0, 0, 0, 0)
        self.GLViagens.setObjectName("GLViagens")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 981, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.GLArtes = QtWidgets.QGridLayout(self.layoutWidget1)
        self.GLArtes.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLArtes.setContentsMargins(0, 0, 0, 0)
        self.GLArtes.setObjectName("GLArtes")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 320, 241, 241))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.GLLances = QtWidgets.QGridLayout(self.layoutWidget2)
        self.GLLances.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLLances.setContentsMargins(0, 0, 0, 0)
        self.GLLances.setObjectName("GLLances")
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(280, 320, 341, 241))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.GLCategorias = QtWidgets.QGridLayout(self.layoutWidget3)
        self.GLCategorias.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLCategorias.setContentsMargins(0, 0, 0, 0)
        self.GLCategorias.setObjectName("GLCategorias")
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(640, 320, 361, 241))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.GLAmostCat = QtWidgets.QGridLayout(self.layoutWidget4)
        self.GLAmostCat.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLAmostCat.setContentsMargins(0, 0, 0, 0)
        self.GLAmostCat.setObjectName("GLAmostCat")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 300, 997, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(263, 307, 16, 257))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(9, 557, 1001, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(623, 308, 15, 256))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setWindowModality(QtCore.Qt.WindowModal)
        self.line_6.setGeometry(QtCore.QRect(10, 0, 999, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(1000, 8, 16, 557))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(2, 7, 16, 557))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.LBwhois = QtWidgets.QLabel(Form)
        self.LBwhois.setGeometry(QtCore.QRect(8, 570, 1000, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBwhois.setFont(font)
        self.LBwhois.setFrameShape(QtWidgets.QFrame.Box)
        self.LBwhois.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LBwhois.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LBwhois.setObjectName("LBwhois")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ficha de Recolha"))
        self.LBwhois.setText(_translate("Form", "UserName: Chernomirdin Da Costa Macuvele"))

import icons_rc
