# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_Ficha_Recolha_TESTE_XI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1160, 722)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("#Form{background-image: url(:/newPrefix/Background/Almora.jpg);}")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 180, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(435, 187, 20, 240))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(0, 420, 1171, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(765, 187, 20, 240))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(-10, 670, 1171, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(989, 427, 31, 251))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(738, 428, 41, 251))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(195, 428, 21, 251))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 1141, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.GLViagens = QtWidgets.QGridLayout(self.layoutWidget)
        self.GLViagens.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLViagens.setContentsMargins(0, 0, 0, 0)
        self.GLViagens.setObjectName("GLViagens")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 190, 431, 231))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.GLArtes = QtWidgets.QGridLayout(self.layoutWidget1)
        self.GLArtes.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLArtes.setContentsMargins(0, 0, 0, 0)
        self.GLArtes.setObjectName("GLArtes")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(450, 190, 321, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.GLLances = QtWidgets.QGridLayout(self.layoutWidget2)
        self.GLLances.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLLances.setContentsMargins(0, 0, 0, 0)
        self.GLLances.setObjectName("GLLances")
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(780, 190, 371, 231))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.GLCategorias = QtWidgets.QGridLayout(self.layoutWidget3)
        self.GLCategorias.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLCategorias.setContentsMargins(0, 0, 0, 0)
        self.GLCategorias.setObjectName("GLCategorias")
        self.layoutWidget4 = QtWidgets.QWidget(Form)
        self.layoutWidget4.setGeometry(QtCore.QRect(8, 441, 191, 231))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.GLAmostCat = QtWidgets.QGridLayout(self.layoutWidget4)
        self.GLAmostCat.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLAmostCat.setContentsMargins(0, 0, 0, 0)
        self.GLAmostCat.setObjectName("GLAmostCat")
        self.layoutWidget5 = QtWidgets.QWidget(Form)
        self.layoutWidget5.setGeometry(QtCore.QRect(206, 439, 331, 231))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.GLEspecies = QtWidgets.QGridLayout(self.layoutWidget5)
        self.GLEspecies.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.GLEspecies.setContentsMargins(0, 0, 0, 0)
        self.GLEspecies.setObjectName("GLEspecies")
        self.layoutWidget6 = QtWidgets.QWidget(Form)
        self.layoutWidget6.setGeometry(QtCore.QRect(540, 440, 211, 231))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.GLAmostEspe = QtWidgets.QGridLayout(self.layoutWidget6)
        self.GLAmostEspe.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.GLAmostEspe.setContentsMargins(0, 0, 0, 0)
        self.GLAmostEspe.setObjectName("GLAmostEspe")
        self.layoutWidget7 = QtWidgets.QWidget(Form)
        self.layoutWidget7.setGeometry(QtCore.QRect(760, 440, 241, 231))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.GLSexo = QtWidgets.QGridLayout(self.layoutWidget7)
        self.GLSexo.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.GLSexo.setContentsMargins(0, 0, 0, 0)
        self.GLSexo.setObjectName("GLSexo")
        self.layoutWidget8 = QtWidgets.QWidget(Form)
        self.layoutWidget8.setGeometry(QtCore.QRect(1010, 440, 141, 231))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.GLComprimentos = QtWidgets.QGridLayout(self.layoutWidget8)
        self.GLComprimentos.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLComprimentos.setContentsMargins(0, 0, 0, 0)
        self.GLComprimentos.setObjectName("GLComprimentos")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 680, 1141, 35))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PBNext = QtWidgets.QPushButton(self.layoutWidget_2)
        self.PBNext.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/next-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBNext.setIcon(icon1)
        self.PBNext.setObjectName("PBNext")
        self.gridLayout.addWidget(self.PBNext, 0, 2, 1, 1)
        self.PBBack = QtWidgets.QPushButton(self.layoutWidget_2)
        self.PBBack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBBack.setIcon(icon2)
        self.PBBack.setObjectName("PBBack")
        self.gridLayout.addWidget(self.PBBack, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.PBCancelar = QtWidgets.QPushButton(self.layoutWidget_2)
        self.PBCancelar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/003-error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBCancelar.setIcon(icon3)
        self.PBCancelar.setIconSize(QtCore.QSize(20, 20))
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout.addWidget(self.PBCancelar, 0, 5, 1, 1)
        self.PBVerificar = QtWidgets.QPushButton(self.layoutWidget_2)
        self.PBVerificar.setObjectName("PBVerificar")
        self.gridLayout.addWidget(self.PBVerificar, 0, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ficha de Recolha"))
        self.PBVerificar.setText(_translate("Form", "Verificar"))

import icons_rc
import images_rc
