# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_Ficha_Recolha_Part_I.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmSaidas(object):
    def setupUi(self, frmSaidas):
        frmSaidas.setObjectName("frmSaidas")
        frmSaidas.resize(1073, 696)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmSaidas.sizePolicy().hasHeightForWidth())
        frmSaidas.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmSaidas.setWindowIcon(icon)
        frmSaidas.setStyleSheet("#frmSaidas{\n"
"background-color: #f0f0f0;\n"
"}\n"
"\n"
".QLineEdit {background-color: rgb(255, 255, 255); \n"
"border-radius: 7px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black\n"
"}\n"
"\n"
".QPushButton {\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black\n"
"}\n"
"\n"
".QPushButton:pressed { \n"
"background-color: DodgerBlue; \n"
"}\n"
"\n"
".QPushButton:focus:pressed { \n"
"background-color: DodgerBlue; \n"
"}\n"
"\n"
".QPushButton:focus { \n"
"background-color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover { \n"
"background-color: Gray; \n"
"}\n"
"\n"
"QPushButton:checked { \n"
"background-color: DodgerBlue; \n"
"}\n"
"\n"
"QPushButton:focus:checked { \n"
"background-color: DodgerBlue; \n"
"}\n"
"")
        self.gridLayout_8 = QtWidgets.QGridLayout(frmSaidas)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.GBSaida = QtWidgets.QGroupBox(frmSaidas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBSaida.sizePolicy().hasHeightForWidth())
        self.GBSaida.setSizePolicy(sizePolicy)
        self.GBSaida.setTitle("")
        self.GBSaida.setObjectName("GBSaida")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GBSaida)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CBCentroPesca = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBCentroPesca.setFont(font)
        self.CBCentroPesca.setObjectName("CBCentroPesca")
        self.gridLayout_2.addWidget(self.CBCentroPesca, 10, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 13, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 13, 1, 1, 1)
        self.TEInicioAmost = QtWidgets.QTimeEdit(self.GBSaida)
        self.TEInicioAmost.setObjectName("TEInicioAmost")
        self.gridLayout_2.addWidget(self.TEInicioAmost, 14, 0, 1, 1)
        self.TEFimAmost = QtWidgets.QTimeEdit(self.GBSaida)
        self.TEFimAmost.setObjectName("TEFimAmost")
        self.gridLayout_2.addWidget(self.TEFimAmost, 14, 1, 1, 1)
        self.CBRegistadores = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBRegistadores.setFont(font)
        self.CBRegistadores.setObjectName("CBRegistadores")
        self.gridLayout_2.addWidget(self.CBRegistadores, 16, 0, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 17, 0, 1, 2)
        self.CBDiaSemana = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBDiaSemana.setFont(font)
        self.CBDiaSemana.setObjectName("CBDiaSemana")
        self.gridLayout_2.addWidget(self.CBDiaSemana, 18, 0, 1, 2)
        self.CBProvincia = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBProvincia.setFont(font)
        self.CBProvincia.setObjectName("CBProvincia")
        self.gridLayout_2.addWidget(self.CBProvincia, 4, 0, 1, 2)
        self.CBDistrito = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBDistrito.setFont(font)
        self.CBDistrito.setObjectName("CBDistrito")
        self.gridLayout_2.addWidget(self.CBDistrito, 6, 0, 1, 2)
        self.CBPosto = QtWidgets.QComboBox(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBPosto.setFont(font)
        self.CBPosto.setObjectName("CBPosto")
        self.gridLayout_2.addWidget(self.CBPosto, 8, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 9, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 2)
        self.LEN_Sequencial = QtWidgets.QLineEdit(self.GBSaida)
        self.LEN_Sequencial.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LEN_Sequencial.setFont(font)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.gridLayout_2.addWidget(self.LEN_Sequencial, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 11, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 15, 0, 1, 2)
        self.DEDataAmost = QtWidgets.QDateTimeEdit(self.GBSaida)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DEDataAmost.setFont(font)
        self.DEDataAmost.setMinimumDate(QtCore.QDate(1800, 12, 31))
        self.DEDataAmost.setObjectName("DEDataAmost")
        self.gridLayout_2.addWidget(self.DEDataAmost, 12, 0, 1, 2)
        self.CBDistrito.raise_()
        self.CBCentroPesca.raise_()
        self.DEDataAmost.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.TEInicioAmost.raise_()
        self.TEFimAmost.raise_()
        self.label_8.raise_()
        self.CBRegistadores.raise_()
        self.label_31.raise_()
        self.CBDiaSemana.raise_()
        self.CBProvincia.raise_()
        self.CBPosto.raise_()
        self.label.raise_()
        self.label_12.raise_()
        self.LEN_Sequencial.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.gridLayout_8.addWidget(self.GBSaida, 0, 0, 2, 1)
        self.GBDadosHidro = QtWidgets.QGroupBox(frmSaidas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBDadosHidro.sizePolicy().hasHeightForWidth())
        self.GBDadosHidro.setSizePolicy(sizePolicy)
        self.GBDadosHidro.setTitle("")
        self.GBDadosHidro.setObjectName("GBDadosHidro")
        self.gridLayout = QtWidgets.QGridLayout(self.GBDadosHidro)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 2)
        self.CBForca = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBForca.setFont(font)
        self.CBForca.setObjectName("CBForca")
        self.gridLayout_3.addWidget(self.CBForca, 1, 0, 1, 2)
        self.TEHoraVent = QtWidgets.QTimeEdit(self.GBDadosHidro)
        self.TEHoraVent.setCurrentSectionIndex(0)
        self.TEHoraVent.setTimeSpec(QtCore.Qt.LocalTime)
        self.TEHoraVent.setTime(QtCore.QTime(0, 0, 0))
        self.TEHoraVent.setObjectName("TEHoraVent")
        self.gridLayout_3.addWidget(self.TEHoraVent, 3, 3, 1, 1)
        self.CBDireccao = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBDireccao.setFont(font)
        self.CBDireccao.setObjectName("CBDireccao")
        self.gridLayout_3.addWidget(self.CBDireccao, 1, 2, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 3, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_33 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_7.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 0, 1, 1, 1)
        self.CBTipoMare = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBTipoMare.setFont(font)
        self.CBTipoMare.setObjectName("CBTipoMare")
        self.gridLayout_7.addWidget(self.CBTipoMare, 1, 0, 1, 1)
        self.CBNivelMare = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBNivelMare.setFont(font)
        self.CBNivelMare.setObjectName("CBNivelMare")
        self.gridLayout_7.addWidget(self.CBNivelMare, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_28 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 1, 0, 1, 1)
        self.DSBPreaiaMar = QtWidgets.QDoubleSpinBox(self.GBDadosHidro)
        self.DSBPreaiaMar.setSuffix("")
        self.DSBPreaiaMar.setMinimum(-1.0)
        self.DSBPreaiaMar.setProperty("value", -1.0)
        self.DSBPreaiaMar.setObjectName("DSBPreaiaMar")
        self.gridLayout_10.addWidget(self.DSBPreaiaMar, 1, 1, 1, 1)
        self.TEPreiamarHora = QtWidgets.QTimeEdit(self.GBDadosHidro)
        self.TEPreiamarHora.setObjectName("TEPreiamarHora")
        self.gridLayout_10.addWidget(self.TEPreiamarHora, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 2, 0, 1, 1)
        self.DSBBaixaMar = QtWidgets.QDoubleSpinBox(self.GBDadosHidro)
        self.DSBBaixaMar.setSuffix("")
        self.DSBBaixaMar.setMinimum(-1.0)
        self.DSBBaixaMar.setProperty("value", -1.0)
        self.DSBBaixaMar.setObjectName("DSBBaixaMar")
        self.gridLayout_10.addWidget(self.DSBBaixaMar, 2, 1, 1, 1)
        self.TEBaixamarHora = QtWidgets.QTimeEdit(self.GBDadosHidro)
        self.TEBaixamarHora.setObjectName("TEBaixamarHora")
        self.gridLayout_10.addWidget(self.TEBaixamarHora, 2, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 0, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_10, 5, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_38 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 0, 1, 1, 1)
        self.CBNebulosidade = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBNebulosidade.setFont(font)
        self.CBNebulosidade.setObjectName("CBNebulosidade")
        self.gridLayout_11.addWidget(self.CBNebulosidade, 1, 1, 1, 1)
        self.TENebulosidadeHora = QtWidgets.QTimeEdit(self.GBDadosHidro)
        self.TENebulosidadeHora.setObjectName("TENebulosidadeHora")
        self.gridLayout_11.addWidget(self.TENebulosidadeHora, 2, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 0, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 2, 1, 1, 1)
        self.CBFaselua = QtWidgets.QComboBox(self.GBDadosHidro)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CBFaselua.setFont(font)
        self.CBFaselua.setObjectName("CBFaselua")
        self.gridLayout_11.addWidget(self.CBFaselua, 1, 2, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_11, 6, 0, 1, 1)
        self.gridLayout_8.addWidget(self.GBDadosHidro, 0, 1, 1, 1)
        self.GBAcividades = QtWidgets.QGroupBox(frmSaidas)
        self.GBAcividades.setEnabled(True)
        self.GBAcividades.setTitle("")
        self.GBAcividades.setObjectName("GBAcividades")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.GBAcividades)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_43 = QtWidgets.QLabel(self.GBAcividades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_15.addWidget(self.label_43, 0, 0, 1, 1)
        self.GBSaidasObs = QtWidgets.QGroupBox(self.GBAcividades)
        self.GBSaidasObs.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBSaidasObs.sizePolicy().hasHeightForWidth())
        self.GBSaidasObs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GBSaidasObs.setFont(font)
        self.GBSaidasObs.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.GBSaidasObs.setFlat(False)
        self.GBSaidasObs.setCheckable(False)
        self.GBSaidasObs.setChecked(False)
        self.GBSaidasObs.setObjectName("GBSaidasObs")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.GBSaidasObs)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.PBSaidasObs = QtWidgets.QPushButton(self.GBSaidasObs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBSaidasObs.sizePolicy().hasHeightForWidth())
        self.PBSaidasObs.setSizePolicy(sizePolicy)
        self.PBSaidasObs.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBSaidasObs.setIcon(icon1)
        self.PBSaidasObs.setIconSize(QtCore.QSize(22, 22))
        self.PBSaidasObs.setObjectName("PBSaidasObs")
        self.gridLayout_14.addWidget(self.PBSaidasObs, 1, 2, 1, 1)
        self.PBEditarSaidasObs = QtWidgets.QPushButton(self.GBSaidasObs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBEditarSaidasObs.sizePolicy().hasHeightForWidth())
        self.PBEditarSaidasObs.setSizePolicy(sizePolicy)
        self.PBEditarSaidasObs.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/005-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBEditarSaidasObs.setIcon(icon2)
        self.PBEditarSaidasObs.setIconSize(QtCore.QSize(22, 22))
        self.PBEditarSaidasObs.setObjectName("PBEditarSaidasObs")
        self.gridLayout_14.addWidget(self.PBEditarSaidasObs, 1, 0, 1, 1)
        self.TVSaidasObservacoes = QtWidgets.QTableView(self.GBSaidasObs)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TVSaidasObservacoes.setFont(font)
        self.TVSaidasObservacoes.setObjectName("TVSaidasObservacoes")
        self.gridLayout_14.addWidget(self.TVSaidasObservacoes, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem1, 1, 1, 1, 1)
        self.gridLayout_15.addWidget(self.GBSaidasObs, 0, 1, 2, 1)
        self.GBActiPesqueira = QtWidgets.QGroupBox(self.GBAcividades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBActiPesqueira.sizePolicy().hasHeightForWidth())
        self.GBActiPesqueira.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.GBActiPesqueira.setFont(font)
        self.GBActiPesqueira.setTitle("")
        self.GBActiPesqueira.setFlat(False)
        self.GBActiPesqueira.setCheckable(False)
        self.GBActiPesqueira.setChecked(False)
        self.GBActiPesqueira.setObjectName("GBActiPesqueira")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.GBActiPesqueira)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.CHBActividade = QtWidgets.QCheckBox(self.GBActiPesqueira)
        self.CHBActividade.setObjectName("CHBActividade")
        self.gridLayout_13.addWidget(self.CHBActividade, 0, 0, 1, 2)
        self.label_40 = QtWidgets.QLabel(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_13.addWidget(self.label_40, 1, 0, 1, 1)
        self.SBActivas = QtWidgets.QSpinBox(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SBActivas.setFont(font)
        self.SBActivas.setReadOnly(True)
        self.SBActivas.setMinimum(-1)
        self.SBActivas.setMaximum(10000)
        self.SBActivas.setProperty("value", -1)
        self.SBActivas.setObjectName("SBActivas")
        self.gridLayout_13.addWidget(self.SBActivas, 1, 1, 1, 1)
        self.SBAmostras = QtWidgets.QSpinBox(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SBAmostras.setFont(font)
        self.SBAmostras.setReadOnly(True)
        self.SBAmostras.setMinimum(-1)
        self.SBAmostras.setMaximum(10000)
        self.SBAmostras.setProperty("value", -1)
        self.SBAmostras.setObjectName("SBAmostras")
        self.gridLayout_13.addWidget(self.SBAmostras, 2, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_13.addWidget(self.label_39, 2, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_13.addWidget(self.label_41, 4, 0, 1, 1)
        self.SBNaoActivas = QtWidgets.QSpinBox(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SBNaoActivas.setFont(font)
        self.SBNaoActivas.setReadOnly(False)
        self.SBNaoActivas.setMinimum(-1)
        self.SBNaoActivas.setMaximum(10000)
        self.SBNaoActivas.setProperty("value", -1)
        self.SBNaoActivas.setObjectName("SBNaoActivas")
        self.gridLayout_13.addWidget(self.SBNaoActivas, 4, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_13.addWidget(self.label_42, 7, 0, 1, 1)
        self.SBOutrosCentros = QtWidgets.QSpinBox(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SBOutrosCentros.setFont(font)
        self.SBOutrosCentros.setMinimum(-1)
        self.SBOutrosCentros.setMaximum(10000)
        self.SBOutrosCentros.setProperty("value", -1)
        self.SBOutrosCentros.setObjectName("SBOutrosCentros")
        self.gridLayout_13.addWidget(self.SBOutrosCentros, 7, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.GBActiPesqueira, 1, 0, 1, 1)
        self.GBArtes = QtWidgets.QGroupBox(self.GBAcividades)
        self.GBArtes.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBArtes.sizePolicy().hasHeightForWidth())
        self.GBArtes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GBArtes.setFont(font)
        self.GBArtes.setAlignment(QtCore.Qt.AlignCenter)
        self.GBArtes.setFlat(False)
        self.GBArtes.setObjectName("GBArtes")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GBArtes)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.PBEditarArtes = QtWidgets.QPushButton(self.GBArtes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBEditarArtes.sizePolicy().hasHeightForWidth())
        self.PBEditarArtes.setSizePolicy(sizePolicy)
        self.PBEditarArtes.setText("")
        self.PBEditarArtes.setIcon(icon2)
        self.PBEditarArtes.setIconSize(QtCore.QSize(22, 22))
        self.PBEditarArtes.setObjectName("PBEditarArtes")
        self.gridLayout_5.addWidget(self.PBEditarArtes, 1, 3, 1, 1)
        self.PBArtes = QtWidgets.QPushButton(self.GBArtes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBArtes.sizePolicy().hasHeightForWidth())
        self.PBArtes.setSizePolicy(sizePolicy)
        self.PBArtes.setText("")
        self.PBArtes.setIcon(icon1)
        self.PBArtes.setIconSize(QtCore.QSize(22, 22))
        self.PBArtes.setObjectName("PBArtes")
        self.gridLayout_5.addWidget(self.PBArtes, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 1, 1, 1)
        self.TVArtesAmost = QtWidgets.QTableView(self.GBArtes)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TVArtesAmost.sizePolicy().hasHeightForWidth())
        self.TVArtesAmost.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.TVArtesAmost.setFont(font)
        self.TVArtesAmost.setObjectName("TVArtesAmost")
        self.gridLayout_5.addWidget(self.TVArtesAmost, 0, 0, 1, 4)
        self.gridLayout_15.addWidget(self.GBArtes, 2, 0, 1, 2)
        self.gridLayout_8.addWidget(self.GBAcividades, 0, 2, 2, 1)
        self.GBObservacoes = QtWidgets.QGroupBox(frmSaidas)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBObservacoes.sizePolicy().hasHeightForWidth())
        self.GBObservacoes.setSizePolicy(sizePolicy)
        self.GBObservacoes.setMaximumSize(QtCore.QSize(16777215, 135))
        self.GBObservacoes.setTitle("")
        self.GBObservacoes.setObjectName("GBObservacoes")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.GBObservacoes)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.PTEObservacao = QtWidgets.QPlainTextEdit(self.GBObservacoes)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PTEObservacao.setFont(font)
        self.PTEObservacao.setObjectName("PTEObservacao")
        self.gridLayout_6.addWidget(self.PTEObservacao, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.GBObservacoes)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.GBObservacoes, 1, 1, 1, 1)
        self.LBwhois = QtWidgets.QLabel(frmSaidas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LBwhois.setFont(font)
        self.LBwhois.setFrameShape(QtWidgets.QFrame.Box)
        self.LBwhois.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LBwhois.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LBwhois.setObjectName("LBwhois")
        self.gridLayout_8.addWidget(self.LBwhois, 3, 0, 1, 3)
        self.GBButtons = QtWidgets.QGroupBox(frmSaidas)
        self.GBButtons.setObjectName("GBButtons")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.GBButtons)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem4 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem4, 0, 5, 1, 1)
        self.PBPesquisar = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBPesquisar.sizePolicy().hasHeightForWidth())
        self.PBPesquisar.setSizePolicy(sizePolicy)
        self.PBPesquisar.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/001-search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBPesquisar.setIcon(icon3)
        self.PBPesquisar.setIconSize(QtCore.QSize(19, 15))
        self.PBPesquisar.setObjectName("PBPesquisar")
        self.gridLayout_12.addWidget(self.PBPesquisar, 0, 3, 1, 1)
        self.PBGuardar = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBGuardar.sizePolicy().hasHeightForWidth())
        self.PBGuardar.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/002-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBGuardar.setIcon(icon4)
        self.PBGuardar.setIconSize(QtCore.QSize(19, 15))
        self.PBGuardar.setObjectName("PBGuardar")
        self.gridLayout_12.addWidget(self.PBGuardar, 0, 0, 1, 1)
        self.PBAmostras = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBAmostras.sizePolicy().hasHeightForWidth())
        self.PBAmostras.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBAmostras.setIcon(icon5)
        self.PBAmostras.setIconSize(QtCore.QSize(19, 15))
        self.PBAmostras.setFlat(False)
        self.PBAmostras.setObjectName("PBAmostras")
        self.gridLayout_12.addWidget(self.PBAmostras, 0, 7, 1, 1)
        self.PBCancelar = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCancelar.sizePolicy().hasHeightForWidth())
        self.PBCancelar.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/003-error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBCancelar.setIcon(icon6)
        self.PBCancelar.setIconSize(QtCore.QSize(19, 15))
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout_12.addWidget(self.PBCancelar, 0, 9, 1, 1)
        self.PBAdicionar = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBAdicionar.sizePolicy().hasHeightForWidth())
        self.PBAdicionar.setSizePolicy(sizePolicy)
        self.PBAdicionar.setIcon(icon1)
        self.PBAdicionar.setIconSize(QtCore.QSize(19, 15))
        self.PBAdicionar.setCheckable(True)
        self.PBAdicionar.setObjectName("PBAdicionar")
        self.gridLayout_12.addWidget(self.PBAdicionar, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(81, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(248, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem6, 0, 8, 1, 1)
        self.PBEditar = QtWidgets.QPushButton(self.GBButtons)
        self.PBEditar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBEditar.sizePolicy().hasHeightForWidth())
        self.PBEditar.setSizePolicy(sizePolicy)
        self.PBEditar.setIcon(icon2)
        self.PBEditar.setIconSize(QtCore.QSize(19, 15))
        self.PBEditar.setCheckable(True)
        self.PBEditar.setObjectName("PBEditar")
        self.gridLayout_12.addWidget(self.PBEditar, 0, 4, 1, 1)
        self.PBFoto = QtWidgets.QPushButton(self.GBButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBFoto.sizePolicy().hasHeightForWidth())
        self.PBFoto.setSizePolicy(sizePolicy)
        self.PBFoto.setIconSize(QtCore.QSize(19, 15))
        self.PBFoto.setFlat(False)
        self.PBFoto.setObjectName("PBFoto")
        self.gridLayout_12.addWidget(self.PBFoto, 0, 6, 1, 1)
        self.gridLayout_8.addWidget(self.GBButtons, 2, 0, 1, 3)

        self.retranslateUi(frmSaidas)
        QtCore.QMetaObject.connectSlotsByName(frmSaidas)

    def retranslateUi(self, frmSaidas):
        _translate = QtCore.QCoreApplication.translate
        frmSaidas.setWindowTitle(_translate("frmSaidas", "Ficha de Recolha"))
        self.label_2.setText(_translate("frmSaidas", "Inicio"))
        self.label_3.setText(_translate("frmSaidas", "Fim"))
        self.TEInicioAmost.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.TEFimAmost.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.label_31.setText(_translate("frmSaidas", "Dia da Semana"))
        self.label.setText(_translate("frmSaidas", "Centro de Pesca"))
        self.label_12.setText(_translate("frmSaidas", "Numero Sequencial"))
        self.label_6.setText(_translate("frmSaidas", "Provincia"))
        self.label_5.setText(_translate("frmSaidas", "Distrito"))
        self.label_4.setText(_translate("frmSaidas", "Posto Administrativo"))
        self.label_7.setText(_translate("frmSaidas", "Data"))
        self.label_9.setText(_translate("frmSaidas", "Saidas"))
        self.label_8.setText(_translate("frmSaidas", "Registador"))
        self.DEDataAmost.setSpecialValueText(_translate("frmSaidas", "--/--/-----"))
        self.DEDataAmost.setDisplayFormat(_translate("frmSaidas", "dd/MM/yyyy"))
        self.label_10.setText(_translate("frmSaidas", "Dados Hidrometeorologicos"))
        self.label_11.setText(_translate("frmSaidas", "VENTO"))
        self.label_13.setText(_translate("frmSaidas", "Hora:       "))
        self.label_26.setText(_translate("frmSaidas", "Direccao"))
        self.TEHoraVent.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.label_25.setText(_translate("frmSaidas", "Forca"))
        self.label_35.setText(_translate("frmSaidas", "MARE"))
        self.label_33.setText(_translate("frmSaidas", "Tipo"))
        self.label_34.setText(_translate("frmSaidas", "Nivel"))
        self.label_28.setText(_translate("frmSaidas", "Hora"))
        self.label_30.setText(_translate("frmSaidas", "Preia-mar "))
        self.DSBPreaiaMar.setSpecialValueText(_translate("frmSaidas", "-,--"))
        self.TEPreiamarHora.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.label_29.setText(_translate("frmSaidas", "Baixa-mar "))
        self.DSBBaixaMar.setSpecialValueText(_translate("frmSaidas", "-,--"))
        self.TEBaixamarHora.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.label_32.setText(_translate("frmSaidas", "Altura - metros"))
        self.label_38.setText(_translate("frmSaidas", "NEBULOSIDADE"))
        self.TENebulosidadeHora.setSpecialValueText(_translate("frmSaidas", "--:--"))
        self.label_37.setText(_translate("frmSaidas", "Hora:        "))
        self.label_36.setText(_translate("frmSaidas", "FASE DA LUA"))
        self.label_43.setText(_translate("frmSaidas", "Actividade Pesqueira"))
        self.GBSaidasObs.setTitle(_translate("frmSaidas", "Saidas Observacoes"))
        self.CHBActividade.setText(_translate("frmSaidas", "Houve activdades pesqueiras?"))
        self.label_40.setText(_translate("frmSaidas", "Activas"))
        self.SBActivas.setSpecialValueText(_translate("frmSaidas", "-"))
        self.SBAmostras.setSpecialValueText(_translate("frmSaidas", "-"))
        self.label_39.setText(_translate("frmSaidas", "Amostradas"))
        self.label_41.setText(_translate("frmSaidas", "Nao Activas"))
        self.SBNaoActivas.setSpecialValueText(_translate("frmSaidas", "-"))
        self.label_42.setText(_translate("frmSaidas", "Outros Centros"))
        self.SBOutrosCentros.setSpecialValueText(_translate("frmSaidas", "-"))
        self.GBArtes.setTitle(_translate("frmSaidas", "Artes"))
        self.label_49.setText(_translate("frmSaidas", "Observacao"))
        self.LBwhois.setText(_translate("frmSaidas", "UserName: Chernomirdin Da Costa Macuvele"))
        self.PBPesquisar.setText(_translate("frmSaidas", "Search"))
        self.PBGuardar.setText(_translate("frmSaidas", "Guardar"))
        self.PBAmostras.setText(_translate("frmSaidas", "Amostras"))
        self.PBCancelar.setText(_translate("frmSaidas", "Cancelar"))
        self.PBAdicionar.setText(_translate("frmSaidas", "Adicionar"))
        self.PBEditar.setText(_translate("frmSaidas", "Editar"))
        self.PBFoto.setText(_translate("frmSaidas", "+ Foto"))

import icons_rc
import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmSaidas = QtWidgets.QWidget()
    ui = Ui_frmSaidas()
    ui.setupUi(frmSaidas)
    frmSaidas.show()
    sys.exit(app.exec_())

