# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_imageToPDF.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 430)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PTEInfo = QtWidgets.QPlainTextEdit(Form)
        self.PTEInfo.setObjectName("PTEInfo")
        self.gridLayout_3.addWidget(self.PTEInfo, 9, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 8, 0, 1, 2)
        self.LECentroPesca = QtWidgets.QLineEdit(Form)
        self.LECentroPesca.setReadOnly(True)
        self.LECentroPesca.setObjectName("LECentroPesca")
        self.gridLayout_3.addWidget(self.LECentroPesca, 5, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PBSave = QtWidgets.QPushButton(Form)
        self.PBSave.setObjectName("PBSave")
        self.gridLayout.addWidget(self.PBSave, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.PBCancel = QtWidgets.QPushButton(Form)
        self.PBCancel.setObjectName("PBCancel")
        self.gridLayout.addWidget(self.PBCancel, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 11, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PBAdd = QtWidgets.QPushButton(Form)
        self.PBAdd.setObjectName("PBAdd")
        self.gridLayout_2.addWidget(self.PBAdd, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.PBremove = QtWidgets.QPushButton(Form)
        self.PBremove.setObjectName("PBremove")
        self.gridLayout_2.addWidget(self.PBremove, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 10, 2, 1, 1)
        self.LWidgetPaths = QtWidgets.QListWidget(Form)
        self.LWidgetPaths.setObjectName("LWidgetPaths")
        self.gridLayout_3.addWidget(self.LWidgetPaths, 0, 2, 10, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 4, 0, 1, 2)
        self.LEN_Sequencial = QtWidgets.QLineEdit(Form)
        self.LEN_Sequencial.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LEN_Sequencial.setFont(font)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.gridLayout_3.addWidget(self.LEN_Sequencial, 1, 0, 1, 1)
        self.LERegistadores = QtWidgets.QLineEdit(Form)
        self.LERegistadores.setReadOnly(True)
        self.LERegistadores.setObjectName("LERegistadores")
        self.gridLayout_3.addWidget(self.LERegistadores, 7, 0, 1, 2)
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.LEDataAmost = QtWidgets.QLineEdit(Form)
        self.LEDataAmost.setReadOnly(True)
        self.LEDataAmost.setObjectName("LEDataAmost")
        self.gridLayout_3.addWidget(self.LEDataAmost, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ficha Scan"))
        self.label_9.setText(_translate("Form", "Info."))
        self.label_8.setText(_translate("Form", "Registador"))
        self.PBSave.setText(_translate("Form", "Guardar"))
        self.PBCancel.setText(_translate("Form", "Cancelar"))
        self.PBAdd.setText(_translate("Form", "+"))
        self.PBremove.setText(_translate("Form", "R"))
        self.label.setText(_translate("Form", "Centro de Pesca"))
        self.label_12.setText(_translate("Form", "Codigo"))
        self.label_7.setText(_translate("Form", "Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

