# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(844, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(1260, 1280))
        MainWindow.setStyleSheet(".QPushButton {\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black\n"
"}\n"
".QPushButton:pressed { background-color: orange; \n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black\n"
"}\n"
"\n"
"\n"
"")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 844, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuDados = QtWidgets.QMenu(self.menubar)
        self.menuDados.setObjectName("menuDados")
        self.menuExportar_Informacao = QtWidgets.QMenu(self.menuDados)
        self.menuExportar_Informacao.setObjectName("menuExportar_Informacao")
        self.menuProcessar = QtWidgets.QMenu(self.menubar)
        self.menuProcessar.setObjectName("menuProcessar")
        self.menuRelatorios = QtWidgets.QMenu(self.menubar)
        self.menuRelatorios.setObjectName("menuRelatorios")
        self.menuGraficos = QtWidgets.QMenu(self.menubar)
        self.menuGraficos.setObjectName("menuGraficos")
        self.menuConsultas = QtWidgets.QMenu(self.menubar)
        self.menuConsultas.setObjectName("menuConsultas")
        self.menuConfiguracao = QtWidgets.QMenu(self.menubar)
        self.menuConfiguracao.setObjectName("menuConfiguracao")
        self.menuRegras = QtWidgets.QMenu(self.menuConfiguracao)
        self.menuRegras.setObjectName("menuRegras")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdicionar_Composicao_Especifica = QtWidgets.QAction(MainWindow)
        self.actionAdicionar_Composicao_Especifica.setObjectName("actionAdicionar_Composicao_Especifica")
        self.actionImportar_Informacao = QtWidgets.QAction(MainWindow)
        self.actionImportar_Informacao.setObjectName("actionImportar_Informacao")
        self.actionReparar_Compactar_Base_de_Dados = QtWidgets.QAction(MainWindow)
        self.actionReparar_Compactar_Base_de_Dados.setObjectName("actionReparar_Compactar_Base_de_Dados")
        self.actionBackup_da_Base_de_Dados = QtWidgets.QAction(MainWindow)
        self.actionBackup_da_Base_de_Dados.setObjectName("actionBackup_da_Base_de_Dados")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionProvincias = QtWidgets.QAction(MainWindow)
        self.actionProvincias.setObjectName("actionProvincias")
        self.actionDistritos = QtWidgets.QAction(MainWindow)
        self.actionDistritos.setObjectName("actionDistritos")
        self.actionEstratos = QtWidgets.QAction(MainWindow)
        self.actionEstratos.setObjectName("actionEstratos")
        self.actioncentros_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actioncentros_de_Pesca.setObjectName("actioncentros_de_Pesca")
        self.actionTipos_de_Centros = QtWidgets.QAction(MainWindow)
        self.actionTipos_de_Centros.setObjectName("actionTipos_de_Centros")
        self.actionLocais_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionLocais_de_Pesca.setObjectName("actionLocais_de_Pesca")
        self.actionCategorias_da_Captura = QtWidgets.QAction(MainWindow)
        self.actionCategorias_da_Captura.setObjectName("actionCategorias_da_Captura")
        self.actionEspecies = QtWidgets.QAction(MainWindow)
        self.actionEspecies.setObjectName("actionEspecies")
        self.actionHabitat = QtWidgets.QAction(MainWindow)
        self.actionHabitat.setObjectName("actionHabitat")
        self.actionGrupos_de_Gestao = QtWidgets.QAction(MainWindow)
        self.actionGrupos_de_Gestao.setObjectName("actionGrupos_de_Gestao")
        self.actionTipo_de_Unidade_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Unidade_de_Pesca.setObjectName("actionTipo_de_Unidade_de_Pesca")
        self.actionArtes_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionArtes_de_Pesca.setObjectName("actionArtes_de_Pesca")
        self.actionDias_da_Semana = QtWidgets.QAction(MainWindow)
        self.actionDias_da_Semana.setObjectName("actionDias_da_Semana")
        self.actionTipo_de_Dia = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Dia.setObjectName("actionTipo_de_Dia")
        self.actionPeriodos_do_Dia = QtWidgets.QAction(MainWindow)
        self.actionPeriodos_do_Dia.setObjectName("actionPeriodos_do_Dia")
        self.actionTipo_de_Periodo = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Periodo.setObjectName("actionTipo_de_Periodo")
        self.actionUnidades_de_Comercializacao = QtWidgets.QAction(MainWindow)
        self.actionUnidades_de_Comercializacao.setObjectName("actionUnidades_de_Comercializacao")
        self.actionFactores_Ambientais = QtWidgets.QAction(MainWindow)
        self.actionFactores_Ambientais.setObjectName("actionFactores_Ambientais")
        self.actionFacores_Socio_Economicos = QtWidgets.QAction(MainWindow)
        self.actionFacores_Socio_Economicos.setObjectName("actionFacores_Socio_Economicos")
        self.actionDirecao_do_Vento = QtWidgets.QAction(MainWindow)
        self.actionDirecao_do_Vento.setObjectName("actionDirecao_do_Vento")
        self.actionForca_do_Vento = QtWidgets.QAction(MainWindow)
        self.actionForca_do_Vento.setObjectName("actionForca_do_Vento")
        self.actionEstado_da_Mate = QtWidgets.QAction(MainWindow)
        self.actionEstado_da_Mate.setObjectName("actionEstado_da_Mate")
        self.actionTipo_de_Mare = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Mare.setObjectName("actionTipo_de_Mare")
        self.actionNebulosidade = QtWidgets.QAction(MainWindow)
        self.actionNebulosidade.setObjectName("actionNebulosidade")
        self.actionFases_da_Lua = QtWidgets.QAction(MainWindow)
        self.actionFases_da_Lua.setObjectName("actionFases_da_Lua")
        self.actionRegistadores = QtWidgets.QAction(MainWindow)
        self.actionRegistadores.setObjectName("actionRegistadores")
        self.actionSexo = QtWidgets.QAction(MainWindow)
        self.actionSexo.setObjectName("actionSexo")
        self.actionTipo_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Pesca.setObjectName("actionTipo_de_Pesca")
        self.actionTipo_de_Grupo_da_Especie = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Grupo_da_Especie.setObjectName("actionTipo_de_Grupo_da_Especie")
        self.actionGrupo_da_Especie = QtWidgets.QAction(MainWindow)
        self.actionGrupo_da_Especie.setObjectName("actionGrupo_da_Especie")
        self.actionSaidas = QtWidgets.QAction(MainWindow)
        self.actionSaidas.setObjectName("actionSaidas")
        self.actionArtes = QtWidgets.QAction(MainWindow)
        self.actionArtes.setObjectName("actionArtes")
        self.actionUndiades = QtWidgets.QAction(MainWindow)
        self.actionUndiades.setObjectName("actionUndiades")
        self.actionLances = QtWidgets.QAction(MainWindow)
        self.actionLances.setObjectName("actionLances")
        self.actionCategorias = QtWidgets.QAction(MainWindow)
        self.actionCategorias.setObjectName("actionCategorias")
        self.actionEspecies_2 = QtWidgets.QAction(MainWindow)
        self.actionEspecies_2.setObjectName("actionEspecies_2")
        self.actionComprimentos = QtWidgets.QAction(MainWindow)
        self.actionComprimentos.setObjectName("actionComprimentos")
        self.actionComercializacao = QtWidgets.QAction(MainWindow)
        self.actionComercializacao.setObjectName("actionComercializacao")
        self.actionValidadr_Informacao = QtWidgets.QAction(MainWindow)
        self.actionValidadr_Informacao.setObjectName("actionValidadr_Informacao")
        self.actionCalculo_das_Estimativas = QtWidgets.QAction(MainWindow)
        self.actionCalculo_das_Estimativas.setObjectName("actionCalculo_das_Estimativas")
        self.actionSaidas_Por_Centro_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionSaidas_Por_Centro_de_Pesca.setObjectName("actionSaidas_Por_Centro_de_Pesca")
        self.actiontTipoBarco = QtWidgets.QAction(MainWindow)
        self.actiontTipoBarco.setObjectName("actiontTipoBarco")
        self.actionUniEsforco = QtWidgets.QAction(MainWindow)
        self.actionUniEsforco.setObjectName("actionUniEsforco")
        self.actionUniTrabalho = QtWidgets.QAction(MainWindow)
        self.actionUniTrabalho.setObjectName("actionUniTrabalho")
        self.actionCentros_to_Tipos_de_Centros = QtWidgets.QAction(MainWindow)
        self.actionCentros_to_Tipos_de_Centros.setObjectName("actionCentros_to_Tipos_de_Centros")
        self.actionCentros_to_Estratos = QtWidgets.QAction(MainWindow)
        self.actionCentros_to_Estratos.setObjectName("actionCentros_to_Estratos")
        self.actionEspecies_to_Categorias = QtWidgets.QAction(MainWindow)
        self.actionEspecies_to_Categorias.setObjectName("actionEspecies_to_Categorias")
        self.actionEspecies_to_Grupo_de_Especies = QtWidgets.QAction(MainWindow)
        self.actionEspecies_to_Grupo_de_Especies.setObjectName("actionEspecies_to_Grupo_de_Especies")
        self.actionEspeceis_to_Habitat = QtWidgets.QAction(MainWindow)
        self.actionEspeceis_to_Habitat.setObjectName("actionEspeceis_to_Habitat")
        self.actionEspecies_to_Distritos = QtWidgets.QAction(MainWindow)
        self.actionEspecies_to_Distritos.setObjectName("actionEspecies_to_Distritos")
        self.actionEspecies_to_Nome_Local_to_Centros = QtWidgets.QAction(MainWindow)
        self.actionEspecies_to_Nome_Local_to_Centros.setObjectName("actionEspecies_to_Nome_Local_to_Centros")
        self.actionTabela_De_Codificadores = QtWidgets.QAction(MainWindow)
        self.actionTabela_De_Codificadores.setObjectName("actionTabela_De_Codificadores")
        self.actionArtes_de_Pesca_2 = QtWidgets.QAction(MainWindow)
        self.actionArtes_de_Pesca_2.setObjectName("actionArtes_de_Pesca_2")
        self.actionCodificadores = QtWidgets.QAction(MainWindow)
        self.actionCodificadores.setObjectName("actionCodificadores")
        self.actionEspecies_3 = QtWidgets.QAction(MainWindow)
        self.actionEspecies_3.setObjectName("actionEspecies_3")
        self.actionNivel = QtWidgets.QAction(MainWindow)
        self.actionNivel.setObjectName("actionNivel")
        self.actionTipo_de_Local = QtWidgets.QAction(MainWindow)
        self.actionTipo_de_Local.setObjectName("actionTipo_de_Local")
        self.actionDias_da_Semana_2 = QtWidgets.QAction(MainWindow)
        self.actionDias_da_Semana_2.setObjectName("actionDias_da_Semana_2")
        self.actionGeometric = QtWidgets.QAction(MainWindow)
        self.actionGeometric.setObjectName("actionGeometric")
        self.actionSaidas_2 = QtWidgets.QAction(MainWindow)
        self.actionSaidas_2.setObjectName("actionSaidas_2")
        self.actionSaidas_Observacoes = QtWidgets.QAction(MainWindow)
        self.actionSaidas_Observacoes.setObjectName("actionSaidas_Observacoes")
        self.actionArtes_Amostradas = QtWidgets.QAction(MainWindow)
        self.actionArtes_Amostradas.setObjectName("actionArtes_Amostradas")
        self.actionUnidade_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionUnidade_de_Pesca.setObjectName("actionUnidade_de_Pesca")
        self.actionViagem_de_Pesca = QtWidgets.QAction(MainWindow)
        self.actionViagem_de_Pesca.setObjectName("actionViagem_de_Pesca")
        self.actionLances_de_pesca = QtWidgets.QAction(MainWindow)
        self.actionLances_de_pesca.setObjectName("actionLances_de_pesca")
        self.actionCategoria_Comercial = QtWidgets.QAction(MainWindow)
        self.actionCategoria_Comercial.setObjectName("actionCategoria_Comercial")
        self.actionAmostra_de_Especie = QtWidgets.QAction(MainWindow)
        self.actionAmostra_de_Especie.setObjectName("actionAmostra_de_Especie")
        self.actionAmostra_de_Sexo = QtWidgets.QAction(MainWindow)
        self.actionAmostra_de_Sexo.setObjectName("actionAmostra_de_Sexo")
        self.actionFicha_de_Recolha_de_Dados = QtWidgets.QAction(MainWindow)
        self.actionFicha_de_Recolha_de_Dados.setObjectName("actionFicha_de_Recolha_de_Dados")
        self.actionTabelas_de_Referencia = QtWidgets.QAction(MainWindow)
        self.actionTabelas_de_Referencia.setObjectName("actionTabelas_de_Referencia")
        self.actionTabelas_de_Referencia_2 = QtWidgets.QAction(MainWindow)
        self.actionTabelas_de_Referencia_2.setObjectName("actionTabelas_de_Referencia_2")
        self.actionTabelas_Relacionais = QtWidgets.QAction(MainWindow)
        self.actionTabelas_Relacionais.setObjectName("actionTabelas_Relacionais")
        self.actionAtribuir_Regras = QtWidgets.QAction(MainWindow)
        self.actionAtribuir_Regras.setObjectName("actionAtribuir_Regras")
        self.actionRegistar = QtWidgets.QAction(MainWindow)
        self.actionRegistar.setObjectName("actionRegistar")
        self.actionEditar = QtWidgets.QAction(MainWindow)
        self.actionEditar.setObjectName("actionEditar")
        self.menuExportar_Informacao.addAction(self.actionSaidas)
        self.menuExportar_Informacao.addAction(self.actionArtes)
        self.menuExportar_Informacao.addAction(self.actionUndiades)
        self.menuExportar_Informacao.addAction(self.actionLances)
        self.menuExportar_Informacao.addAction(self.actionCategorias)
        self.menuExportar_Informacao.addAction(self.actionEspecies_2)
        self.menuExportar_Informacao.addAction(self.actionComprimentos)
        self.menuExportar_Informacao.addAction(self.actionComercializacao)
        self.menuDados.addAction(self.actionFicha_de_Recolha_de_Dados)
        self.menuDados.addAction(self.actionAdicionar_Composicao_Especifica)
        self.menuDados.addSeparator()
        self.menuDados.addAction(self.actionTabelas_de_Referencia)
        self.menuDados.addAction(self.actionTabelas_Relacionais)
        self.menuDados.addSeparator()
        self.menuDados.addAction(self.menuExportar_Informacao.menuAction())
        self.menuDados.addAction(self.actionImportar_Informacao)
        self.menuDados.addAction(self.actionReparar_Compactar_Base_de_Dados)
        self.menuDados.addAction(self.actionBackup_da_Base_de_Dados)
        self.menuDados.addSeparator()
        self.menuDados.addAction(self.actionSair)
        self.menuProcessar.addAction(self.actionValidadr_Informacao)
        self.menuProcessar.addSeparator()
        self.menuProcessar.addAction(self.actionCalculo_das_Estimativas)
        self.menuConsultas.addAction(self.actionSaidas_Por_Centro_de_Pesca)
        self.menuRegras.addAction(self.actionRegistar)
        self.menuRegras.addAction(self.actionEditar)
        self.menuConfiguracao.addAction(self.menuRegras.menuAction())
        self.menubar.addAction(self.menuDados.menuAction())
        self.menubar.addAction(self.menuProcessar.menuAction())
        self.menubar.addAction(self.menuRelatorios.menuAction())
        self.menubar.addAction(self.menuGraficos.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())
        self.menubar.addAction(self.menuConfiguracao.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pescar 2.0"))
        self.menuDados.setTitle(_translate("MainWindow", "Dados"))
        self.menuExportar_Informacao.setTitle(_translate("MainWindow", "Exportar Informacao"))
        self.menuProcessar.setTitle(_translate("MainWindow", "Processar"))
        self.menuRelatorios.setTitle(_translate("MainWindow", "Relatorios"))
        self.menuGraficos.setTitle(_translate("MainWindow", "Graficos"))
        self.menuConsultas.setTitle(_translate("MainWindow", "Consultas"))
        self.menuConfiguracao.setTitle(_translate("MainWindow", "Configuracao"))
        self.menuRegras.setTitle(_translate("MainWindow", "Regras"))
        self.actionAdicionar_Composicao_Especifica.setText(_translate("MainWindow", "Adicionar Composicao Especifica"))
        self.actionImportar_Informacao.setText(_translate("MainWindow", "Importar Informacao"))
        self.actionReparar_Compactar_Base_de_Dados.setText(_translate("MainWindow", "Reparar/Compactar Base de Dados"))
        self.actionBackup_da_Base_de_Dados.setText(_translate("MainWindow", "Backup da Base de Dados"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionProvincias.setText(_translate("MainWindow", "Provincias"))
        self.actionDistritos.setText(_translate("MainWindow", "Distritos"))
        self.actionEstratos.setText(_translate("MainWindow", "Estratos"))
        self.actioncentros_de_Pesca.setText(_translate("MainWindow", "Centros de Pesca"))
        self.actionTipos_de_Centros.setText(_translate("MainWindow", "Tipos de Centros"))
        self.actionLocais_de_Pesca.setText(_translate("MainWindow", "Locais de Pesca"))
        self.actionCategorias_da_Captura.setText(_translate("MainWindow", "Categorias da Captura"))
        self.actionEspecies.setText(_translate("MainWindow", "Especies"))
        self.actionHabitat.setText(_translate("MainWindow", "Habitat"))
        self.actionGrupos_de_Gestao.setText(_translate("MainWindow", "Grupos de Gestao"))
        self.actionTipo_de_Unidade_de_Pesca.setText(_translate("MainWindow", "Tipo de Unidade de Pesca"))
        self.actionArtes_de_Pesca.setText(_translate("MainWindow", "Artes de Pesca"))
        self.actionDias_da_Semana.setText(_translate("MainWindow", "Dias da Semana"))
        self.actionTipo_de_Dia.setText(_translate("MainWindow", "Tipo de Dia"))
        self.actionPeriodos_do_Dia.setText(_translate("MainWindow", "Periodos do Dia"))
        self.actionTipo_de_Periodo.setText(_translate("MainWindow", "Tipo de Periodo"))
        self.actionUnidades_de_Comercializacao.setText(_translate("MainWindow", "Unidades de Comercializacao"))
        self.actionFactores_Ambientais.setText(_translate("MainWindow", "Factores  Ambientais"))
        self.actionFacores_Socio_Economicos.setText(_translate("MainWindow", "Facores Socio-Economicos"))
        self.actionDirecao_do_Vento.setText(_translate("MainWindow", "Direcao do Vento"))
        self.actionForca_do_Vento.setText(_translate("MainWindow", "Forca do Vento"))
        self.actionEstado_da_Mate.setText(_translate("MainWindow", "Estado da Mare"))
        self.actionTipo_de_Mare.setText(_translate("MainWindow", "Tipo de Mare"))
        self.actionNebulosidade.setText(_translate("MainWindow", "Nebulosidade"))
        self.actionFases_da_Lua.setText(_translate("MainWindow", "Fases da Lua"))
        self.actionRegistadores.setText(_translate("MainWindow", "Registadores"))
        self.actionSexo.setText(_translate("MainWindow", "Sexo"))
        self.actionTipo_de_Pesca.setText(_translate("MainWindow", "Tipo de Pesca"))
        self.actionTipo_de_Grupo_da_Especie.setText(_translate("MainWindow", "Tipo de Grupo da Especie"))
        self.actionGrupo_da_Especie.setText(_translate("MainWindow", "Grupo da Especie"))
        self.actionSaidas.setText(_translate("MainWindow", "Saidas"))
        self.actionArtes.setText(_translate("MainWindow", "Artes"))
        self.actionUndiades.setText(_translate("MainWindow", "Undiades "))
        self.actionLances.setText(_translate("MainWindow", "Lances"))
        self.actionCategorias.setText(_translate("MainWindow", "Categorias"))
        self.actionEspecies_2.setText(_translate("MainWindow", "Especies"))
        self.actionComprimentos.setText(_translate("MainWindow", "Comprimentos"))
        self.actionComercializacao.setText(_translate("MainWindow", "Comercializacao"))
        self.actionValidadr_Informacao.setText(_translate("MainWindow", "Validadr Informacao"))
        self.actionCalculo_das_Estimativas.setText(_translate("MainWindow", "Calculo das Estimativas"))
        self.actionSaidas_Por_Centro_de_Pesca.setText(_translate("MainWindow", "Saidas Por Centro de Pesca"))
        self.actiontTipoBarco.setText(_translate("MainWindow", "Tipo de Barco"))
        self.actionUniEsforco.setText(_translate("MainWindow", "Unitfade de Esforco"))
        self.actionUniTrabalho.setText(_translate("MainWindow", "Unidade de Trabalho"))
        self.actionCentros_to_Tipos_de_Centros.setText(_translate("MainWindow", "Centros to Tipos de Centros"))
        self.actionCentros_to_Estratos.setText(_translate("MainWindow", "Centros to Estratos"))
        self.actionEspecies_to_Categorias.setText(_translate("MainWindow", "Especies to Categorias"))
        self.actionEspecies_to_Grupo_de_Especies.setText(_translate("MainWindow", "Especies to Grupo de Especies"))
        self.actionEspeceis_to_Habitat.setText(_translate("MainWindow", "Especeis to Habitat"))
        self.actionEspecies_to_Distritos.setText(_translate("MainWindow", "Especies to Distritos"))
        self.actionEspecies_to_Nome_Local_to_Centros.setText(_translate("MainWindow", "Especies to Nome Local to Centros"))
        self.actionTabela_De_Codificadores.setText(_translate("MainWindow", "Tabela De Codificadores"))
        self.actionArtes_de_Pesca_2.setText(_translate("MainWindow", "Artes de Pesca"))
        self.actionCodificadores.setText(_translate("MainWindow", "Codificadores"))
        self.actionEspecies_3.setText(_translate("MainWindow", "Especies"))
        self.actionNivel.setText(_translate("MainWindow", "Nivel"))
        self.actionTipo_de_Local.setText(_translate("MainWindow", "Tipo de Local"))
        self.actionDias_da_Semana_2.setText(_translate("MainWindow", "Dias da Semana"))
        self.actionGeometric.setText(_translate("MainWindow", "Geometric"))
        self.actionSaidas_2.setText(_translate("MainWindow", "Saidas"))
        self.actionSaidas_Observacoes.setText(_translate("MainWindow", "Saidas Observacoes"))
        self.actionArtes_Amostradas.setText(_translate("MainWindow", "Artes Amostradas"))
        self.actionUnidade_de_Pesca.setText(_translate("MainWindow", "Unidade de Pesca"))
        self.actionViagem_de_Pesca.setText(_translate("MainWindow", "Viagem de Pesca"))
        self.actionLances_de_pesca.setText(_translate("MainWindow", "Lances de pesca"))
        self.actionCategoria_Comercial.setText(_translate("MainWindow", "Categoria Comercial"))
        self.actionAmostra_de_Especie.setText(_translate("MainWindow", "Amostra de Especie"))
        self.actionAmostra_de_Sexo.setText(_translate("MainWindow", "Amostra de Sexo"))
        self.actionFicha_de_Recolha_de_Dados.setText(_translate("MainWindow", "Ficha de Recolha de Dados"))
        self.actionTabelas_de_Referencia.setText(_translate("MainWindow", "Tabelas de Referencia"))
        self.actionTabelas_de_Referencia_2.setText(_translate("MainWindow", "Tabelas de Referencia"))
        self.actionTabelas_Relacionais.setText(_translate("MainWindow", "Tabelas Relacionais"))
        self.actionAtribuir_Regras.setText(_translate("MainWindow", "Atribuir Regras"))
        self.actionRegistar.setText(_translate("MainWindow", "Registar"))
        self.actionEditar.setText(_translate("MainWindow", "Editar "))

import images_rc
