# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_MenuTypes.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(700, 205)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(680, 128))
        Form.setMaximumSize(QtCore.QSize(700, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/stats-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(3.0)
        Form.setStyleSheet("#Form{\n"
"background-color: #ffffff; \n"
"}\n"
"\n"
".QPushButton {\n"
"border-radius: 12px;\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: black\n"
"}\n"
"\n"
".QPushButton:pressed { \n"
"background-color: DodgerBlue; \n"
"}\n"
"\n"
".QPushButton:focus:pressed { \n"
"background-color: #3c3c3c; \n"
"}\n"
"\n"
".QPushButton:focus { \n"
"background-color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover { \n"
"background-color: Gray; \n"
"}\n"
"\n"
"QPushButton:checked { \n"
"background-color: DodgerBlue; \n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PBIntClass = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBIntClass.sizePolicy().hasHeightForWidth())
        self.PBIntClass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBIntClass.setFont(font)
        self.PBIntClass.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PBIntClass.setObjectName("PBIntClass")
        self.gridLayout.addWidget(self.PBIntClass, 0, 5, 1, 1)
        self.PBOutros = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBOutros.sizePolicy().hasHeightForWidth())
        self.PBOutros.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBOutros.setFont(font)
        self.PBOutros.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/001-more.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBOutros.setIcon(icon1)
        self.PBOutros.setFlat(False)
        self.PBOutros.setObjectName("PBOutros")
        self.gridLayout.addWidget(self.PBOutros, 1, 4, 1, 1)
        self.PBEspecies = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBEspecies.sizePolicy().hasHeightForWidth())
        self.PBEspecies.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBEspecies.setFont(font)
        self.PBEspecies.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/fish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBEspecies.setIcon(icon2)
        self.PBEspecies.setObjectName("PBEspecies")
        self.gridLayout.addWidget(self.PBEspecies, 0, 1, 1, 1)
        self.PBNivel = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBNivel.sizePolicy().hasHeightForWidth())
        self.PBNivel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBNivel.setFont(font)
        self.PBNivel.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/layers.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBNivel.setIcon(icon3)
        self.PBNivel.setObjectName("PBNivel")
        self.gridLayout.addWidget(self.PBNivel, 1, 1, 1, 1)
        self.PBCodificadores = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCodificadores.sizePolicy().hasHeightForWidth())
        self.PBCodificadores.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBCodificadores.setFont(font)
        self.PBCodificadores.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/008-chains.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBCodificadores.setIcon(icon4)
        self.PBCodificadores.setObjectName("PBCodificadores")
        self.gridLayout.addWidget(self.PBCodificadores, 0, 0, 1, 1)
        self.PBArtes = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBArtes.sizePolicy().hasHeightForWidth())
        self.PBArtes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBArtes.setFont(font)
        self.PBArtes.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/007-fishing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBArtes.setIcon(icon5)
        self.PBArtes.setObjectName("PBArtes")
        self.gridLayout.addWidget(self.PBArtes, 0, 2, 1, 1)
        self.PBTipUniPesca = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBTipUniPesca.sizePolicy().hasHeightForWidth())
        self.PBTipUniPesca.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBTipUniPesca.setFont(font)
        self.PBTipUniPesca.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PBTipUniPesca.setFlat(False)
        self.PBTipUniPesca.setObjectName("PBTipUniPesca")
        self.gridLayout.addWidget(self.PBTipUniPesca, 1, 5, 1, 1)
        self.PBTipLocal = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBTipLocal.sizePolicy().hasHeightForWidth())
        self.PBTipLocal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBTipLocal.setFont(font)
        self.PBTipLocal.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/002-placeholders.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBTipLocal.setIcon(icon6)
        self.PBTipLocal.setObjectName("PBTipLocal")
        self.gridLayout.addWidget(self.PBTipLocal, 1, 3, 1, 1)
        self.PBEspaco = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBEspaco.sizePolicy().hasHeightForWidth())
        self.PBEspaco.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBEspaco.setFont(font)
        self.PBEspaco.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/005-placeholder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBEspaco.setIcon(icon7)
        self.PBEspaco.setObjectName("PBEspaco")
        self.gridLayout.addWidget(self.PBEspaco, 1, 0, 1, 1)
        self.PBDiaSemana = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBDiaSemana.sizePolicy().hasHeightForWidth())
        self.PBDiaSemana.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBDiaSemana.setFont(font)
        self.PBDiaSemana.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/006-wall-calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBDiaSemana.setIcon(icon8)
        self.PBDiaSemana.setObjectName("PBDiaSemana")
        self.gridLayout.addWidget(self.PBDiaSemana, 0, 3, 1, 1)
        self.PBRegistadores = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBRegistadores.sizePolicy().hasHeightForWidth())
        self.PBRegistadores.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBRegistadores.setFont(font)
        self.PBRegistadores.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PBRegistadores.setIcon(icon1)
        self.PBRegistadores.setFlat(False)
        self.PBRegistadores.setObjectName("PBRegistadores")
        self.gridLayout.addWidget(self.PBRegistadores, 0, 4, 1, 1)
        self.PBPesqueiros = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBPesqueiros.sizePolicy().hasHeightForWidth())
        self.PBPesqueiros.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PBPesqueiros.setFont(font)
        self.PBPesqueiros.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PBPesqueiros.setIcon(icon1)
        self.PBPesqueiros.setFlat(False)
        self.PBPesqueiros.setObjectName("PBPesqueiros")
        self.gridLayout.addWidget(self.PBPesqueiros, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("#label {background-color: #f0f0f0}")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Referencias"))
        self.PBIntClass.setText(_translate("Form", "int. Class"))
        self.PBOutros.setText(_translate("Form", "Ref. Comum"))
        self.PBEspecies.setText(_translate("Form", "Especies"))
        self.PBNivel.setText(_translate("Form", "Nivel"))
        self.PBCodificadores.setText(_translate("Form", "Tipos de Ref"))
        self.PBArtes.setText(_translate("Form", "Artes"))
        self.PBTipUniPesca.setText(_translate("Form", "Tip. Uni. \n"
"Pesca"))
        self.PBTipLocal.setText(_translate("Form", "Tipo de Local"))
        self.PBEspaco.setText(_translate("Form", "Espaco"))
        self.PBDiaSemana.setText(_translate("Form", "Dias Da Semana"))
        self.PBRegistadores.setText(_translate("Form", "Registadores"))
        self.PBPesqueiros.setText(_translate("Form", "Pesqueiros"))
        self.label.setText(_translate("Form", "Selecione a Referencia "))

import icons_rc
import images_rc
