# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_Rules.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(518, 483)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CBTipoRegra = QtWidgets.QComboBox(Form)
        self.CBTipoRegra.setObjectName("CBTipoRegra")
        self.gridLayout_2.addWidget(self.CBTipoRegra, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.LECodigo = QtWidgets.QLineEdit(Form)
        self.LECodigo.setObjectName("LECodigo")
        self.gridLayout_2.addWidget(self.LECodigo, 0, 2, 1, 1)
        self.PTEMsg = QtWidgets.QPlainTextEdit(Form)
        self.PTEMsg.setObjectName("PTEMsg")
        self.gridLayout_2.addWidget(self.PTEMsg, 4, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PBPrev = QtWidgets.QPushButton(Form)
        self.PBPrev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBPrev.setIcon(icon)
        self.PBPrev.setObjectName("PBPrev")
        self.gridLayout.addWidget(self.PBPrev, 0, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.PBNext = QtWidgets.QPushButton(Form)
        self.PBNext.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/next-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBNext.setIcon(icon1)
        self.PBNext.setObjectName("PBNext")
        self.gridLayout.addWidget(self.PBNext, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.PBAdd = QtWidgets.QPushButton(Form)
        self.PBAdd.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBAdd.setIcon(icon2)
        self.PBAdd.setObjectName("PBAdd")
        self.gridLayout.addWidget(self.PBAdd, 0, 4, 1, 1)
        self.PBSave = QtWidgets.QPushButton(Form)
        self.PBSave.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/002-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBSave.setIcon(icon3)
        self.PBSave.setObjectName("PBSave")
        self.gridLayout.addWidget(self.PBSave, 0, 5, 1, 1)
        self.PBEdit = QtWidgets.QPushButton(Form)
        self.PBEdit.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/005-writer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBEdit.setIcon(icon4)
        self.PBEdit.setObjectName("PBEdit")
        self.gridLayout.addWidget(self.PBEdit, 0, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 7, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.CHBActivo = QtWidgets.QCheckBox(Form)
        self.CHBActivo.setObjectName("CHBActivo")
        self.gridLayout_2.addWidget(self.CHBActivo, 6, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.LECampos = QtWidgets.QLineEdit(Form)
        self.LECampos.setObjectName("LECampos")
        self.gridLayout_2.addWidget(self.LECampos, 3, 2, 1, 1)
        self.PTEDescricao = QtWidgets.QPlainTextEdit(Form)
        self.PTEDescricao.setObjectName("PTEDescricao")
        self.gridLayout_2.addWidget(self.PTEDescricao, 5, 2, 1, 1)
        self.PTERegra = QtWidgets.QPlainTextEdit(Form)
        self.PTERegra.setObjectName("PTERegra")
        self.gridLayout_2.addWidget(self.PTERegra, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Menu de Regras"))
        self.label_3.setText(_translate("Form", "Regra"))
        self.label_4.setText(_translate("Form", "Campos"))
        self.label_6.setText(_translate("Form", "Descricao"))
        self.label.setText(_translate("Form", "Codigo"))
        self.label_5.setText(_translate("Form", "Msg de Erro"))
        self.CHBActivo.setText(_translate("Form", "Activo"))
        self.label_2.setText(_translate("Form", "Tipo de Regra"))

import icons_rc
