# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PscArt2.0.X/UserInt/ui_saidas_Prop.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 593)
        self.gridLayout_13 = QtWidgets.QGridLayout(Form)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.DEDataFim = QtWidgets.QDateEdit(Form)
        self.DEDataFim.setObjectName("DEDataFim")
        self.gridLayout_10.addWidget(self.DEDataFim, 1, 1, 1, 1)
        self.DEDataIncio = QtWidgets.QDateEdit(Form)
        self.DEDataIncio.setObjectName("DEDataIncio")
        self.gridLayout_10.addWidget(self.DEDataIncio, 1, 0, 1, 1)
        self.TVSaidas = QtWidgets.QTableView(Form)
        self.TVSaidas.setObjectName("TVSaidas")
        self.gridLayout_10.addWidget(self.TVSaidas, 2, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_10.addWidget(self.label_26, 0, 0, 1, 2)
        self.PBPesquisar = QtWidgets.QPushButton(Form)
        self.PBPesquisar.setObjectName("PBPesquisar")
        self.gridLayout_10.addWidget(self.PBPesquisar, 3, 0, 1, 2)
        self.gridLayout_13.addLayout(self.gridLayout_10, 4, 0, 5, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.CBTipoMare = QtWidgets.QComboBox(Form)
        self.CBTipoMare.setObjectName("CBTipoMare")
        self.gridLayout_5.addWidget(self.CBTipoMare, 2, 0, 1, 1)
        self.CBNivelMare = QtWidgets.QComboBox(Form)
        self.CBNivelMare.setObjectName("CBNivelMare")
        self.gridLayout_5.addWidget(self.CBNivelMare, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 3)
        self.gridLayout_13.addLayout(self.gridLayout_5, 3, 3, 2, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 2, 1, 1)
        self.TEPreiamarHora = QtWidgets.QTimeEdit(Form)
        self.TEPreiamarHora.setObjectName("TEPreiamarHora")
        self.gridLayout_6.addWidget(self.TEPreiamarHora, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.DSBBaixaMar = QtWidgets.QDoubleSpinBox(Form)
        self.DSBBaixaMar.setObjectName("DSBBaixaMar")
        self.gridLayout_6.addWidget(self.DSBBaixaMar, 2, 1, 1, 1)
        self.TEBaixamarHora = QtWidgets.QTimeEdit(Form)
        self.TEBaixamarHora.setObjectName("TEBaixamarHora")
        self.gridLayout_6.addWidget(self.TEBaixamarHora, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.DSBPreaiaMar = QtWidgets.QDoubleSpinBox(Form)
        self.DSBPreaiaMar.setObjectName("DSBPreaiaMar")
        self.gridLayout_6.addWidget(self.DSBPreaiaMar, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 2)
        self.gridLayout_13.addLayout(self.gridLayout_6, 5, 3, 2, 2)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_32 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 0, 0, 1, 1)
        self.PTEObservacao = QtWidgets.QPlainTextEdit(Form)
        self.PTEObservacao.setObjectName("PTEObservacao")
        self.gridLayout_11.addWidget(self.PTEObservacao, 1, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_11, 6, 6, 3, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_21 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_7.addWidget(self.label_21, 0, 0, 2, 1)
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 2, 1, 1)
        self.TENebulosidadeHora = QtWidgets.QTimeEdit(Form)
        self.TENebulosidadeHora.setObjectName("TENebulosidadeHora")
        self.gridLayout_7.addWidget(self.TENebulosidadeHora, 1, 2, 2, 1)
        self.CBFaselua = QtWidgets.QComboBox(Form)
        self.CBFaselua.setObjectName("CBFaselua")
        self.gridLayout_7.addWidget(self.CBFaselua, 2, 0, 1, 1)
        self.CBNebulosidade = QtWidgets.QComboBox(Form)
        self.CBNebulosidade.setObjectName("CBNebulosidade")
        self.gridLayout_7.addWidget(self.CBNebulosidade, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 1, 2, 1)
        self.gridLayout_13.addLayout(self.gridLayout_7, 7, 3, 1, 2)
        self.splitter_4 = QtWidgets.QSplitter(Form)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 0, 0, 1, 1)
        self.LEN_Sequencial = QtWidgets.QLineEdit(self.layoutWidget)
        self.LEN_Sequencial.setReadOnly(True)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.gridLayout_12.addWidget(self.LEN_Sequencial, 0, 1, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.PBObservacoes = QtWidgets.QPushButton(self.splitter_3)
        self.PBObservacoes.setObjectName("PBObservacoes")
        self.PBArtesSaidas = QtWidgets.QPushButton(self.splitter_3)
        self.PBArtesSaidas.setObjectName("PBArtesSaidas")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.PBEditar = QtWidgets.QPushButton(self.splitter)
        self.PBEditar.setObjectName("PBEditar")
        self.PBGuradar = QtWidgets.QPushButton(self.splitter)
        self.PBGuradar.setObjectName("PBGuradar")
        self.PBInserir = QtWidgets.QPushButton(self.splitter)
        self.PBInserir.setObjectName("PBInserir")
        self.PBCancelar = QtWidgets.QPushButton(self.splitter)
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout_13.addWidget(self.splitter_4, 10, 0, 1, 7)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.CBForca = QtWidgets.QComboBox(Form)
        self.CBForca.setObjectName("CBForca")
        self.gridLayout_4.addWidget(self.CBForca, 1, 0, 1, 1)
        self.CBDireccao = QtWidgets.QComboBox(Form)
        self.CBDireccao.setObjectName("CBDireccao")
        self.gridLayout_4.addWidget(self.CBDireccao, 1, 1, 1, 1)
        self.TEHoraVent = QtWidgets.QTimeEdit(Form)
        self.TEHoraVent.setObjectName("TEHoraVent")
        self.gridLayout_4.addWidget(self.TEHoraVent, 1, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_4, 2, 3, 1, 2)
        self.GBActiPesqueira = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.GBActiPesqueira.setFont(font)
        self.GBActiPesqueira.setCheckable(True)
        self.GBActiPesqueira.setObjectName("GBActiPesqueira")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.GBActiPesqueira)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_27 = QtWidgets.QLabel(self.GBActiPesqueira)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 1, 0, 1, 1)
        self.SBAmostras = QtWidgets.QSpinBox(self.GBActiPesqueira)
        self.SBAmostras.setObjectName("SBAmostras")
        self.gridLayout_8.addWidget(self.SBAmostras, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.GBActiPesqueira)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 2, 0, 1, 1)
        self.SBActivas = QtWidgets.QSpinBox(self.GBActiPesqueira)
        self.SBActivas.setObjectName("SBActivas")
        self.gridLayout_8.addWidget(self.SBActivas, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.GBActiPesqueira)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 3, 0, 1, 1)
        self.SBNaoActivas = QtWidgets.QSpinBox(self.GBActiPesqueira)
        self.SBNaoActivas.setObjectName("SBNaoActivas")
        self.gridLayout_8.addWidget(self.SBNaoActivas, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.GBActiPesqueira)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 4, 0, 1, 1)
        self.SBOutrosCentros = QtWidgets.QSpinBox(self.GBActiPesqueira)
        self.SBOutrosCentros.setObjectName("SBOutrosCentros")
        self.gridLayout_8.addWidget(self.SBOutrosCentros, 4, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.GBActiPesqueira)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 0, 0, 1, 2)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.GBActiPesqueira, 1, 6, 5, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.TEFimAmost = QtWidgets.QTimeEdit(Form)
        self.TEFimAmost.setObjectName("TEFimAmost")
        self.gridLayout.addWidget(self.TEFimAmost, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.DEDataAmost = QtWidgets.QDateEdit(Form)
        self.DEDataAmost.setObjectName("DEDataAmost")
        self.gridLayout.addWidget(self.DEDataAmost, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.TEInicioAmost = QtWidgets.QTimeEdit(Form)
        self.TEInicioAmost.setObjectName("TEInicioAmost")
        self.gridLayout.addWidget(self.TEInicioAmost, 1, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout, 0, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_13.addWidget(self.line_2, 0, 2, 9, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(4)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_13.addWidget(self.line_3, 0, 5, 9, 1)
        self.splitter_2 = QtWidgets.QSplitter(Form)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_9 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.splitter_2, 1, 3, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.LEEstrato = QtWidgets.QLineEdit(Form)
        self.LEEstrato.setReadOnly(True)
        self.LEEstrato.setObjectName("LEEstrato")
        self.gridLayout_2.addWidget(self.LEEstrato, 1, 0, 1, 1)
        self.LEDistrito = QtWidgets.QLineEdit(Form)
        self.LEDistrito.setReadOnly(True)
        self.LEDistrito.setObjectName("LEDistrito")
        self.gridLayout_2.addWidget(self.LEDistrito, 1, 1, 1, 1)
        self.LEProvincia = QtWidgets.QLineEdit(Form)
        self.LEProvincia.setReadOnly(True)
        self.LEProvincia.setObjectName("LEProvincia")
        self.gridLayout_2.addWidget(self.LEProvincia, 1, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_2, 0, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(374, 73, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem, 8, 3, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.CBCentroPesca = QtWidgets.QComboBox(Form)
        self.CBCentroPesca.setObjectName("CBCentroPesca")
        self.gridLayout_3.addWidget(self.CBCentroPesca, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.CBRegistadores = QtWidgets.QComboBox(Form)
        self.CBRegistadores.setObjectName("CBRegistadores")
        self.gridLayout_3.addWidget(self.CBRegistadores, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 4, 0, 1, 1)
        self.CBDiaSemana = QtWidgets.QComboBox(Form)
        self.CBDiaSemana.setObjectName("CBDiaSemana")
        self.gridLayout_3.addWidget(self.CBDiaSemana, 5, 0, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_3, 0, 0, 4, 2)
        self.line_4 = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_4.setFont(font)
        self.line_4.setLineWidth(4)
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_13.addWidget(self.line_4, 9, 0, 1, 7)
        self.splitter_4.raise_()
        self.splitter_2.raise_()
        self.GBActiPesqueira.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Saidas"))
        self.label_26.setText(_translate("Form", "Todas saidas"))
        self.PBPesquisar.setText(_translate("Form", "Pesquisar"))
        self.label_15.setText(_translate("Form", "Tipo"))
        self.label_16.setText(_translate("Form", "Nivel"))
        self.label_14.setText(_translate("Form", "MARE"))
        self.label_18.setText(_translate("Form", "Hora"))
        self.label_20.setText(_translate("Form", "Baixa-mar "))
        self.label_19.setText(_translate("Form", "Preia-mar "))
        self.label_17.setText(_translate("Form", "Altura"))
        self.label_32.setText(_translate("Form", "Observacao"))
        self.label_21.setText(_translate("Form", "FASE DA LUA"))
        self.label_23.setText(_translate("Form", "Hora"))
        self.label_22.setText(_translate("Form", "NEBULOSIDADE - Grau"))
        self.label_33.setText(_translate("Form", "Nº Sequencial"))
        self.PBObservacoes.setText(_translate("Form", "Observacoes"))
        self.PBArtesSaidas.setText(_translate("Form", "Artes das Saidas"))
        self.PBEditar.setText(_translate("Form", "Editar"))
        self.PBGuradar.setText(_translate("Form", "Guardar"))
        self.PBInserir.setText(_translate("Form", "Inserir"))
        self.PBCancelar.setText(_translate("Form", "Cancelar"))
        self.label_11.setText(_translate("Form", "Forca"))
        self.label_12.setText(_translate("Form", "Direccao"))
        self.label_13.setText(_translate("Form", "Hora"))
        self.GBActiPesqueira.setTitle(_translate("Form", "Houve activdades pesqueiras?"))
        self.label_27.setText(_translate("Form", "Amostradas"))
        self.label_29.setText(_translate("Form", "Activas"))
        self.label_28.setText(_translate("Form", "Nao Activas"))
        self.label_30.setText(_translate("Form", "Outros Centros"))
        self.label_25.setText(_translate("Form", "Total das Artes"))
        self.label_2.setText(_translate("Form", "Inicio"))
        self.label_3.setText(_translate("Form", "Fim"))
        self.label_7.setText(_translate("Form", "Data"))
        self.label_9.setText(_translate("Form", "DADOS HIDROMETEOROLOGIOS"))
        self.label_10.setText(_translate("Form", "VENTO"))
        self.label_4.setText(_translate("Form", "Estrato"))
        self.label_5.setText(_translate("Form", "Distrito"))
        self.label_6.setText(_translate("Form", "Provincia"))
        self.label.setText(_translate("Form", "Centro de Pesca"))
        self.label_8.setText(_translate("Form", "Registador"))
        self.label_31.setText(_translate("Form", "Dia da Semana"))

