# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PscArt2.0.X/UserInt/ui_saidas.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1131, 670)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 10, 3, 1, 5)
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 9, 9, 1, 5)
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 11, 9, 1, 2)
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 12, 9, 1, 2)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 2)
        self.LEEstrato = QtWidgets.QLineEdit(Form)
        self.LEEstrato.setObjectName("LEEstrato")
        self.gridLayout.addWidget(self.LEEstrato, 1, 3, 2, 2)
        self.TEBaixamarHora = QtWidgets.QTimeEdit(Form)
        self.TEBaixamarHora.setObjectName("TEBaixamarHora")
        self.gridLayout.addWidget(self.TEBaixamarHora, 15, 7, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 2, 19, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 8, 19, 1)
        self.DEDataAmost = QtWidgets.QDateEdit(Form)
        self.DEDataAmost.setObjectName("DEDataAmost")
        self.gridLayout.addWidget(self.DEDataAmost, 1, 9, 2, 3)
        self.PBPesquisar = QtWidgets.QPushButton(Form)
        self.PBPesquisar.setObjectName("PBPesquisar")
        self.gridLayout.addWidget(self.PBPesquisar, 19, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 6, 1, 2)
        self.TEHoraVent = QtWidgets.QTimeEdit(Form)
        self.TEHoraVent.setObjectName("TEHoraVent")
        self.gridLayout.addWidget(self.TEHoraVent, 8, 6, 1, 2)
        self.CBRegistadores = QtWidgets.QComboBox(Form)
        self.CBRegistadores.setObjectName("CBRegistadores")
        self.gridLayout.addWidget(self.CBRegistadores, 5, 0, 1, 2)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 13, 6, 1, 2)
        self.CBForca = QtWidgets.QComboBox(Form)
        self.CBForca.setObjectName("CBForca")
        self.gridLayout.addWidget(self.CBForca, 8, 3, 1, 2)
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 15, 9, 1, 5)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 11, 6, 1, 2)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 13, 1, 1)
        self.SBAmostras = QtWidgets.QSpinBox(Form)
        self.SBAmostras.setObjectName("SBAmostras")
        self.gridLayout.addWidget(self.SBAmostras, 11, 11, 1, 3)
        self.label_9 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 3, 1, 5)
        self.RBNaoHouve = QtWidgets.QRadioButton(Form)
        self.RBNaoHouve.setObjectName("RBNaoHouve")
        self.gridLayout.addWidget(self.RBNaoHouve, 5, 12, 1, 2)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 10, 9, 1, 5)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 5, 1, 1)
        self.LEProvincia = QtWidgets.QLineEdit(Form)
        self.LEProvincia.setObjectName("LEProvincia")
        self.gridLayout.addWidget(self.LEProvincia, 1, 6, 2, 2)
        self.label_23 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 17, 6, 1, 1)
        self.CBTipoMare = QtWidgets.QComboBox(Form)
        self.CBTipoMare.setObjectName("CBTipoMare")
        self.gridLayout.addWidget(self.CBTipoMare, 12, 3, 1, 2)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 9, 1, 5)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 15, 3, 1, 1)
        self.line_9 = QtWidgets.QFrame(Form)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 18, 3, 1, 5)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 12, 1, 1)
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 13, 9, 1, 2)
        self.LEDistrito = QtWidgets.QLineEdit(Form)
        self.LEDistrito.setObjectName("LEDistrito")
        self.gridLayout.addWidget(self.LEDistrito, 1, 5, 2, 1)
        self.DSBPreaiaMar = QtWidgets.QDoubleSpinBox(Form)
        self.DSBPreaiaMar.setObjectName("DSBPreaiaMar")
        self.gridLayout.addWidget(self.DSBPreaiaMar, 14, 3, 1, 1)
        self.RBhouve = QtWidgets.QRadioButton(Form)
        self.RBhouve.setChecked(True)
        self.RBhouve.setObjectName("RBhouve")
        self.gridLayout.addWidget(self.RBhouve, 5, 9, 1, 3)
        self.TENebulosidadeHora = QtWidgets.QTimeEdit(Form)
        self.TENebulosidadeHora.setObjectName("TENebulosidadeHora")
        self.gridLayout.addWidget(self.TENebulosidadeHora, 17, 7, 1, 1)
        self.DSBBaixaMar = QtWidgets.QDoubleSpinBox(Form)
        self.DSBBaixaMar.setObjectName("DSBBaixaMar")
        self.gridLayout.addWidget(self.DSBBaixaMar, 14, 6, 1, 2)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 9, 1, 5)
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 15, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 9, 1, 3)
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 14, 9, 1, 2)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.PBEditar = QtWidgets.QPushButton(self.splitter)
        self.PBEditar.setObjectName("PBEditar")
        self.PBGuradar = QtWidgets.QPushButton(self.splitter)
        self.PBGuradar.setObjectName("PBGuradar")
        self.PBCancelar = QtWidgets.QPushButton(self.splitter)
        self.PBCancelar.setObjectName("PBCancelar")
        self.PBInserir = QtWidgets.QPushButton(self.splitter)
        self.PBInserir.setObjectName("PBInserir")
        self.gridLayout.addWidget(self.splitter, 19, 6, 1, 8)
        self.CBCentroPesca = QtWidgets.QComboBox(Form)
        self.CBCentroPesca.setObjectName("CBCentroPesca")
        self.gridLayout.addWidget(self.CBCentroPesca, 1, 0, 2, 2)
        self.SBActivas = QtWidgets.QSpinBox(Form)
        self.SBActivas.setObjectName("SBActivas")
        self.gridLayout.addWidget(self.SBActivas, 12, 11, 1, 3)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 3, 1, 2)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 2)
        self.SBNaoActivas = QtWidgets.QSpinBox(Form)
        self.SBNaoActivas.setObjectName("SBNaoActivas")
        self.gridLayout.addWidget(self.SBNaoActivas, 13, 11, 1, 3)
        self.label_8 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 13, 3, 1, 1)
        self.CBNivelMare = QtWidgets.QComboBox(Form)
        self.CBNivelMare.setObjectName("CBNivelMare")
        self.gridLayout.addWidget(self.CBNivelMare, 12, 6, 1, 2)
        self.SBOutrosCentros = QtWidgets.QSpinBox(Form)
        self.SBOutrosCentros.setObjectName("SBOutrosCentros")
        self.gridLayout.addWidget(self.SBOutrosCentros, 14, 11, 1, 3)
        self.label_21 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 16, 3, 1, 2)
        self.CBDireccao = QtWidgets.QComboBox(Form)
        self.CBDireccao.setObjectName("CBDireccao")
        self.gridLayout.addWidget(self.CBDireccao, 8, 5, 1, 1)
        self.DEDataIncio = QtWidgets.QDateEdit(Form)
        self.DEDataIncio.setObjectName("DEDataIncio")
        self.gridLayout.addWidget(self.DEDataIncio, 11, 0, 1, 1)
        self.DEDataFim = QtWidgets.QDateEdit(Form)
        self.DEDataFim.setObjectName("DEDataFim")
        self.gridLayout.addWidget(self.DEDataFim, 11, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 9, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 10, 0, 1, 2)
        self.label_32 = QtWidgets.QLabel(Form)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 17, 9, 2, 1)
        self.CBDiaSemana = QtWidgets.QComboBox(Form)
        self.CBDiaSemana.setObjectName("CBDiaSemana")
        self.gridLayout.addWidget(self.CBDiaSemana, 7, 0, 1, 2)
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 19, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 11, 3, 1, 2)
        self.LEN_Sequencial = QtWidgets.QLineEdit(Form)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.gridLayout.addWidget(self.LEN_Sequencial, 19, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 6, 0, 1, 2)
        self.TEInicioAmost = QtWidgets.QTimeEdit(Form)
        self.TEInicioAmost.setObjectName("TEInicioAmost")
        self.gridLayout.addWidget(self.TEInicioAmost, 1, 12, 2, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 3, 3, 1, 5)
        self.TEPreiamarHora = QtWidgets.QTimeEdit(Form)
        self.TEPreiamarHora.setObjectName("TEPreiamarHora")
        self.gridLayout.addWidget(self.TEPreiamarHora, 15, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 3, 1, 5)
        self.CBFaselua = QtWidgets.QComboBox(Form)
        self.CBFaselua.setObjectName("CBFaselua")
        self.gridLayout.addWidget(self.CBFaselua, 17, 3, 1, 2)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.CBNebulosidade = QtWidgets.QComboBox(Form)
        self.CBNebulosidade.setObjectName("CBNebulosidade")
        self.gridLayout.addWidget(self.CBNebulosidade, 17, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 16, 5, 1, 1)
        self.TEFimAmost = QtWidgets.QTimeEdit(Form)
        self.TEFimAmost.setObjectName("TEFimAmost")
        self.gridLayout.addWidget(self.TEFimAmost, 1, 13, 2, 1)
        self.PTEObservacao = QtWidgets.QPlainTextEdit(Form)
        self.PTEObservacao.setObjectName("PTEObservacao")
        self.gridLayout.addWidget(self.PTEObservacao, 17, 10, 2, 4)
        self.TVSaidas = QtWidgets.QTableView(Form)
        self.TVSaidas.setObjectName("TVSaidas")
        self.gridLayout.addWidget(self.TVSaidas, 12, 0, 7, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_14.setText(_translate("Form", "MARE"))
        self.label.setText(_translate("Form", "Centro de Pesca"))
        self.label_27.setText(_translate("Form", "Amostradas"))
        self.label_29.setText(_translate("Form", "Activas"))
        self.label_6.setText(_translate("Form", "Provincia"))
        self.PBPesquisar.setText(_translate("Form", "Pesquisar"))
        self.label_13.setText(_translate("Form", "Hora"))
        self.label_20.setText(_translate("Form", "Baixa-mar (Altura (m))"))
        self.label_16.setText(_translate("Form", "Nivel"))
        self.label_4.setText(_translate("Form", "Estrato"))
        self.label_3.setText(_translate("Form", "Fim"))
        self.label_9.setText(_translate("Form", "DADOS HIDROMETEOROLOGIOS"))
        self.RBNaoHouve.setText(_translate("Form", "Nao Houve."))
        self.label_25.setText(_translate("Form", "Total das Artes"))
        self.label_12.setText(_translate("Form", "Direccao"))
        self.label_23.setText(_translate("Form", "Hora"))
        self.label_17.setText(_translate("Form", "Houve activdades pesqueiras?"))
        self.label_18.setText(_translate("Form", "Hora"))
        self.label_2.setText(_translate("Form", "Inicio"))
        self.label_28.setText(_translate("Form", "Nao Activas"))
        self.RBhouve.setText(_translate("Form", "Houve."))
        self.label_24.setText(_translate("Form", "Hora"))
        self.label_7.setText(_translate("Form", "Data"))
        self.label_30.setText(_translate("Form", "Outros Centros"))
        self.PBEditar.setText(_translate("Form", "Editar"))
        self.PBGuradar.setText(_translate("Form", "Guardar"))
        self.PBCancelar.setText(_translate("Form", "Cancelar"))
        self.PBInserir.setText(_translate("Form", "Inserir"))
        self.label_11.setText(_translate("Form", "Forca"))
        self.label_8.setText(_translate("Form", "Registador"))
        self.label_19.setText(_translate("Form", "Preia-mar (Altura (m))"))
        self.label_21.setText(_translate("Form", "FASE DA LUA"))
        self.label_26.setText(_translate("Form", "Todas saidas"))
        self.label_32.setText(_translate("Form", "Observacao"))
        self.label_33.setText(_translate("Form", "Numero Sequencial"))
        self.label_15.setText(_translate("Form", "Tipo"))
        self.label_31.setText(_translate("Form", "Dia da Semana"))
        self.label_10.setText(_translate("Form", "VENTOS"))
        self.label_5.setText(_translate("Form", "Distrito"))
        self.label_22.setText(_translate("Form", "NEBULOSIDADE - Grau"))

