# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PscArt2.0.X/UserInt/ui_uniPesca.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(436, 415)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TabMotor_LEModelo = QtWidgets.QLineEdit(self.tab)
        self.TabMotor_LEModelo.setObjectName("TabMotor_LEModelo")
        self.gridLayout_2.addWidget(self.TabMotor_LEModelo, 2, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 3)
        self.TabMotor_LEN_Sequencial = QtWidgets.QLineEdit(self.tab)
        self.TabMotor_LEN_Sequencial.setObjectName("TabMotor_LEN_Sequencial")
        self.gridLayout_2.addWidget(self.TabMotor_LEN_Sequencial, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 3)
        self.TabMotor_LEMarca = QtWidgets.QLineEdit(self.tab)
        self.TabMotor_LEMarca.setObjectName("TabMotor_LEMarca")
        self.gridLayout_2.addWidget(self.TabMotor_LEMarca, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 3)
        self.TabMotor_LEPotencia = QtWidgets.QLineEdit(self.tab)
        self.TabMotor_LEPotencia.setObjectName("TabMotor_LEPotencia")
        self.gridLayout_2.addWidget(self.TabMotor_LEPotencia, 3, 3, 1, 1)
        self.TabMotor_LETipo = QtWidgets.QLineEdit(self.tab)
        self.TabMotor_LETipo.setObjectName("TabMotor_LETipo")
        self.gridLayout_2.addWidget(self.TabMotor_LETipo, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 3)
        self.TabMotor_DEAno = QtWidgets.QDateEdit(self.tab)
        self.TabMotor_DEAno.setObjectName("TabMotor_DEAno")
        self.gridLayout_2.addWidget(self.TabMotor_DEAno, 4, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.TabMotor_TVMotor = QtWidgets.QTableView(self.tab)
        self.TabMotor_TVMotor.setObjectName("TabMotor_TVMotor")
        self.gridLayout_3.addWidget(self.TabMotor_TVMotor, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.TabMotor_PBEditar = QtWidgets.QPushButton(self.splitter)
        self.TabMotor_PBEditar.setObjectName("TabMotor_PBEditar")
        self.TabMotor_PBCancelar = QtWidgets.QPushButton(self.splitter)
        self.TabMotor_PBCancelar.setObjectName("TabMotor_PBCancelar")
        self.TabMotor_PBGuardar = QtWidgets.QPushButton(self.splitter)
        self.TabMotor_PBGuardar.setObjectName("TabMotor_PBGuardar")
        self.TabMotor_PBInseri = QtWidgets.QPushButton(self.splitter)
        self.TabMotor_PBInseri.setObjectName("TabMotor_PBInseri")
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.TabUniPesca_Unipesca = QtWidgets.QTableView(self.tab_2)
        self.TabUniPesca_Unipesca.setGeometry(QtCore.QRect(20, 179, 366, 141))
        self.TabUniPesca_Unipesca.setObjectName("TabUniPesca_Unipesca")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setGeometry(QtCore.QRect(20, 330, 366, 32))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.TabUniPesca_PBEditar = QtWidgets.QPushButton(self.splitter_2)
        self.TabUniPesca_PBEditar.setObjectName("TabUniPesca_PBEditar")
        self.TabUniPesca_PBCancelar = QtWidgets.QPushButton(self.splitter_2)
        self.TabUniPesca_PBCancelar.setObjectName("TabUniPesca_PBCancelar")
        self.TabUniPesca_PBGuardar = QtWidgets.QPushButton(self.splitter_2)
        self.TabUniPesca_PBGuardar.setObjectName("TabUniPesca_PBGuardar")
        self.TabUniPesca_PBInseri = QtWidgets.QPushButton(self.splitter_2)
        self.TabUniPesca_PBInseri.setObjectName("TabUniPesca_PBInseri")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 366, 148))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TabUniPesca_CBMotor = QtWidgets.QComboBox(self.layoutWidget)
        self.TabUniPesca_CBMotor.setObjectName("TabUniPesca_CBMotor")
        self.gridLayout_4.addWidget(self.TabUniPesca_CBMotor, 3, 3, 1, 1)
        self.TabUniPesca_CBArtePrincinpal = QtWidgets.QComboBox(self.layoutWidget)
        self.TabUniPesca_CBArtePrincinpal.setObjectName("TabUniPesca_CBArtePrincinpal")
        self.gridLayout_4.addWidget(self.TabUniPesca_CBArtePrincinpal, 4, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 3)
        self.TabUniPesca_LENome = QtWidgets.QLineEdit(self.layoutWidget)
        self.TabUniPesca_LENome.setObjectName("TabUniPesca_LENome")
        self.gridLayout_4.addWidget(self.TabUniPesca_LENome, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 3)
        self.TabUniPesca_LEN_Sequencial = QtWidgets.QLineEdit(self.layoutWidget)
        self.TabUniPesca_LEN_Sequencial.setObjectName("TabUniPesca_LEN_Sequencial")
        self.gridLayout_4.addWidget(self.TabUniPesca_LEN_Sequencial, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 3)
        self.TabUniPesca_LEMatricula = QtWidgets.QLineEdit(self.layoutWidget)
        self.TabUniPesca_LEMatricula.setObjectName("TabUniPesca_LEMatricula")
        self.gridLayout_4.addWidget(self.TabUniPesca_LEMatricula, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Unidade de pesca"))
        self.label_5.setText(_translate("Form", "Marca"))
        self.label_6.setText(_translate("Form", "Modelo"))
        self.label.setText(_translate("Form", "potencia"))
        self.label_7.setText(_translate("Form", "Ano"))
        self.label_4.setText(_translate("Form", "Numero Sequencial"))
        self.label_2.setText(_translate("Form", "Tipo"))
        self.TabMotor_PBEditar.setText(_translate("Form", "Editar"))
        self.TabMotor_PBCancelar.setText(_translate("Form", "Cancelar"))
        self.TabMotor_PBGuardar.setText(_translate("Form", "Guardar"))
        self.TabMotor_PBInseri.setText(_translate("Form", "Inserir"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Motor"))
        self.TabUniPesca_PBEditar.setText(_translate("Form", "Editar"))
        self.TabUniPesca_PBCancelar.setText(_translate("Form", "Cancelar"))
        self.TabUniPesca_PBGuardar.setText(_translate("Form", "Guardar"))
        self.TabUniPesca_PBInseri.setText(_translate("Form", "Inserir"))
        self.label_11.setText(_translate("Form", "Arte Princinpal"))
        self.label_8.setText(_translate("Form", "Numero Sequencial"))
        self.label_10.setText(_translate("Form", "Motor"))
        self.label_9.setText(_translate("Form", "Nome"))
        self.label_3.setText(_translate("Form", "Matricula"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Unidade de Pesca"))

