# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chernomirdinmacuvele/Documents/workspace/PescArt2.0/UserInt/ui_ViagemPesca.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmViagemPesca(object):
    def setupUi(self, frmViagemPesca):
        frmViagemPesca.setObjectName("frmViagemPesca")
        frmViagemPesca.resize(676, 320)
        frmViagemPesca.setMaximumSize(QtCore.QSize(676, 320))
        frmViagemPesca.setStyleSheet("#Form\n"
"{background-image: url(:/newPrefix/918640-white-wallpaper.jpg);}")
        self.label_25 = QtWidgets.QLabel(frmViagemPesca)
        self.label_25.setGeometry(QtCore.QRect(15, 23, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_29 = QtWidgets.QLabel(frmViagemPesca)
        self.label_29.setGeometry(QtCore.QRect(10, 3, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_61 = QtWidgets.QLabel(frmViagemPesca)
        self.label_61.setGeometry(QtCore.QRect(70, 23, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.line_2 = QtWidgets.QFrame(frmViagemPesca)
        self.line_2.setGeometry(QtCore.QRect(65, 23, 3, 47))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(frmViagemPesca)
        self.line_4.setGeometry(QtCore.QRect(-26, 35, 151, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(frmViagemPesca)
        self.line_5.setGeometry(QtCore.QRect(-16, 16, 141, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(frmViagemPesca)
        self.line_6.setGeometry(QtCore.QRect(126, -1, 3, 71))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_26 = QtWidgets.QLabel(frmViagemPesca)
        self.label_26.setGeometry(QtCore.QRect(130, 2, 77, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.line_7 = QtWidgets.QFrame(frmViagemPesca)
        self.line_7.setGeometry(QtCore.QRect(-3, 64, 681, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(2)
        self.line_7.setMidLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.layoutWidget = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 140, 281, 89))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.DEDataInicio = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.DEDataInicio.setObjectName("DEDataInicio")
        self.gridLayout_15.addWidget(self.DEDataInicio, 1, 1, 1, 1)
        self.DEDataFim = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.DEDataFim.setObjectName("DEDataFim")
        self.gridLayout_15.addWidget(self.DEDataFim, 2, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_15.addWidget(self.label_58, 0, 3, 1, 2)
        self.TEHoraInico = QtWidgets.QTimeEdit(self.layoutWidget)
        self.TEHoraInico.setObjectName("TEHoraInico")
        self.gridLayout_15.addWidget(self.TEHoraInico, 1, 4, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget)
        self.label_56.setObjectName("label_56")
        self.gridLayout_15.addWidget(self.label_56, 2, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout_15.addWidget(self.label_51, 2, 3, 1, 1)
        self.TEHoraFim = QtWidgets.QTimeEdit(self.layoutWidget)
        self.TEHoraFim.setObjectName("TEHoraFim")
        self.gridLayout_15.addWidget(self.TEHoraFim, 2, 4, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget)
        self.label_45.setObjectName("label_45")
        self.gridLayout_15.addWidget(self.label_45, 1, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_15.addWidget(self.label_53, 0, 0, 1, 2)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout_15.addWidget(self.label_54, 1, 0, 1, 1)
        self.CHBInicio = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHBInicio.setText("")
        self.CHBInicio.setChecked(True)
        self.CHBInicio.setObjectName("CHBInicio")
        self.gridLayout_15.addWidget(self.CHBInicio, 1, 2, 1, 1)
        self.CHBFIm = QtWidgets.QCheckBox(self.layoutWidget)
        self.CHBFIm.setText("")
        self.CHBFIm.setChecked(True)
        self.CHBFIm.setObjectName("CHBFIm")
        self.gridLayout_15.addWidget(self.CHBFIm, 2, 2, 1, 1)
        self.line = QtWidgets.QFrame(frmViagemPesca)
        self.line.setGeometry(QtCore.QRect(-3, 127, 691, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 240, 651, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_21.addWidget(self.label_22, 0, 0, 1, 1)
        self.DSBTam_Malha = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.DSBTam_Malha.setMaximum(10000.99)
        self.DSBTam_Malha.setObjectName("DSBTam_Malha")
        self.gridLayout_21.addWidget(self.DSBTam_Malha, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_21.addWidget(self.label_23, 0, 2, 1, 1)
        self.DSBComp_Rede = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.DSBComp_Rede.setMaximum(10000.99)
        self.DSBComp_Rede.setObjectName("DSBComp_Rede")
        self.gridLayout_21.addWidget(self.DSBComp_Rede, 0, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_21.addWidget(self.label_24, 0, 4, 1, 1)
        self.DSBComp_Cabo = QtWidgets.QDoubleSpinBox(self.layoutWidget1)
        self.DSBComp_Cabo.setMaximum(10000.99)
        self.DSBComp_Cabo.setObjectName("DSBComp_Cabo")
        self.gridLayout_21.addWidget(self.DSBComp_Cabo, 0, 5, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget2.setGeometry(QtCore.QRect(300, 140, 373, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.DSBCapTotal = QtWidgets.QDoubleSpinBox(self.layoutWidget2)
        self.DSBCapTotal.setMaximum(10000.99)
        self.DSBCapTotal.setObjectName("DSBCapTotal")
        self.gridLayout_20.addWidget(self.DSBCapTotal, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_20.addWidget(self.label_21, 1, 3, 1, 1)
        self.SBN_Pescadores = QtWidgets.QSpinBox(self.layoutWidget2)
        self.SBN_Pescadores.setMaximum(10000)
        self.SBN_Pescadores.setObjectName("SBN_Pescadores")
        self.gridLayout_20.addWidget(self.SBN_Pescadores, 1, 4, 1, 1)
        self.SBN_Lanc_Total = QtWidgets.QSpinBox(self.layoutWidget2)
        self.SBN_Lanc_Total.setMaximum(10000)
        self.SBN_Lanc_Total.setObjectName("SBN_Lanc_Total")
        self.gridLayout_20.addWidget(self.SBN_Lanc_Total, 0, 2, 1, 1)
        self.SBN_Lanc_Amsotras = QtWidgets.QSpinBox(self.layoutWidget2)
        self.SBN_Lanc_Amsotras.setMaximum(10000)
        self.SBN_Lanc_Amsotras.setObjectName("SBN_Lanc_Amsotras")
        self.gridLayout_20.addWidget(self.SBN_Lanc_Amsotras, 0, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_20.addWidget(self.label_20, 1, 0, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 0, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_20.addWidget(self.label_18, 0, 3, 1, 1)
        self.line_3 = QtWidgets.QFrame(frmViagemPesca)
        self.line_3.setGeometry(QtCore.QRect(-11, 221, 687, 16))
        self.line_3.setLineWidth(2)
        self.line_3.setMidLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.LEN_Sequencial = QtWidgets.QLineEdit(frmViagemPesca)
        self.LEN_Sequencial.setGeometry(QtCore.QRect(70, 45, 51, 21))
        self.LEN_Sequencial.setReadOnly(True)
        self.LEN_Sequencial.setObjectName("LEN_Sequencial")
        self.LEN_Sequencial_Arte = QtWidgets.QLineEdit(frmViagemPesca)
        self.LEN_Sequencial_Arte.setGeometry(QtCore.QRect(10, 45, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEN_Sequencial_Arte.sizePolicy().hasHeightForWidth())
        self.LEN_Sequencial_Arte.setSizePolicy(sizePolicy)
        self.LEN_Sequencial_Arte.setReadOnly(True)
        self.LEN_Sequencial_Arte.setObjectName("LEN_Sequencial_Arte")
        self.SBSeqUnidade = QtWidgets.QSpinBox(frmViagemPesca)
        self.SBSeqUnidade.setGeometry(QtCore.QRect(132, 42, 74, 23))
        self.SBSeqUnidade.setMaximum(10000)
        self.SBSeqUnidade.setObjectName("SBSeqUnidade")
        self.layoutWidget3 = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget3.setGeometry(QtCore.QRect(220, 10, 441, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_57 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout.addWidget(self.label_57, 0, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout.addWidget(self.label_60, 0, 1, 1, 1)
        self.CBPesqueiros = MyComboBox(self.layoutWidget3)
        self.CBPesqueiros.setObjectName("CBPesqueiros")
        self.gridLayout.addWidget(self.CBPesqueiros, 1, 0, 1, 1)
        self.CBUniAmostra = QtWidgets.QComboBox(self.layoutWidget3)
        self.CBUniAmostra.setObjectName("CBUniAmostra")
        self.gridLayout.addWidget(self.CBUniAmostra, 1, 1, 1, 1)
        self.layoutWidget4 = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 80, 641, 51))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LEUniPesca = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEUniPesca.sizePolicy().hasHeightForWidth())
        self.LEUniPesca.setSizePolicy(sizePolicy)
        self.LEUniPesca.setObjectName("LEUniPesca")
        self.gridLayout_2.addWidget(self.LEUniPesca, 2, 1, 1, 1)
        self.CBTipUniPesca = MyComboBox(self.layoutWidget4)
        self.CBTipUniPesca.setObjectName("CBTipUniPesca")
        self.gridLayout_2.addWidget(self.CBTipUniPesca, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 1, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 1, 1, 1, 1)
        self.layoutWidget5 = QtWidgets.QWidget(frmViagemPesca)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 280, 631, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PBSalvar = QtWidgets.QPushButton(self.layoutWidget5)
        self.PBSalvar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/002-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBSalvar.setIcon(icon)
        self.PBSalvar.setObjectName("PBSalvar")
        self.gridLayout_3.addWidget(self.PBSalvar, 0, 0, 1, 1)
        self.PBCancelar = QtWidgets.QPushButton(self.layoutWidget5)
        self.PBCancelar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/Icons/003-error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PBCancelar.setIcon(icon1)
        self.PBCancelar.setObjectName("PBCancelar")
        self.gridLayout_3.addWidget(self.PBCancelar, 0, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(frmViagemPesca)
        self.line_8.setGeometry(QtCore.QRect(210, 0, 3, 71))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(frmViagemPesca)
        self.line_9.setGeometry(QtCore.QRect(289, 135, 12, 91))
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setLineWidth(1)
        self.line_9.setMidLineWidth(3)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")

        self.retranslateUi(frmViagemPesca)
        QtCore.QMetaObject.connectSlotsByName(frmViagemPesca)

    def retranslateUi(self, frmViagemPesca):
        _translate = QtCore.QCoreApplication.translate
        frmViagemPesca.setWindowTitle(_translate("frmViagemPesca", "Viagem de Pesca"))
        self.label_25.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">Arte</span></p></body></html>"))
        self.label_29.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">Nº Sequencial</span></p></body></html>"))
        self.label_61.setText(_translate("frmViagemPesca", "Viagem"))
        self.label_26.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">Nº </span></p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">Sequencial</span></p></body></html>"))
        self.DEDataInicio.setDisplayFormat(_translate("frmViagemPesca", "dd/MM/yyyy"))
        self.DEDataFim.setDisplayFormat(_translate("frmViagemPesca", "dd/MM/yyyy"))
        self.label_58.setText(_translate("frmViagemPesca", "Hora"))
        self.label_56.setText(_translate("frmViagemPesca", "Fim"))
        self.label_51.setText(_translate("frmViagemPesca", "Fim"))
        self.label_45.setText(_translate("frmViagemPesca", "Inico"))
        self.label_53.setText(_translate("frmViagemPesca", "Data"))
        self.label_54.setText(_translate("frmViagemPesca", "Inico"))
        self.label_22.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tamanho da</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Malha</p></body></html>"))
        self.label_23.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Comprimento</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">da Rede</p></body></html>"))
        self.label_24.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Comprimento</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">do Cabo</p></body></html>"))
        self.label_21.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nº de </p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pescadores</p></body></html>"))
        self.label_20.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Captura</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total</p></body></html>"))
        self.label_19.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nº de Total</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> de Lances Amost.</p></body></html>"))
        self.label_18.setText(_translate("frmViagemPesca", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nº de Lances</p>\n"
"<p align=\"center\" style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Amostrados</p></body></html>"))
        self.LEN_Sequencial.setPlaceholderText(_translate("frmViagemPesca", "Ex:1"))
        self.LEN_Sequencial_Arte.setPlaceholderText(_translate("frmViagemPesca", "Ex:1"))
        self.label_57.setText(_translate("frmViagemPesca", "Pesqueiros"))
        self.label_60.setText(_translate("frmViagemPesca", "Unidade de Amostra"))
        self.label_55.setText(_translate("frmViagemPesca", "Tipo de Unidade de Pesca"))
        self.label_52.setText(_translate("frmViagemPesca", "Unidade de Pesca"))

from CustomWidgets import MyComboBox
import icons_rc
import images_rc
